### ISSUE TITLE
Add Haemers graph with alpha-theta-vartheta property

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#1]
G is a 108-regular graph on 220 vertices. The vertices correspond to the 3-element subsets of {1,…,12} and two such vertices are adjacent whenever the subsets intersect in exactly one element. This graph was considered by Haemers, who showed that α(G)=Θ(G)<ϑ(G)

**Comment by nvcleemp** [comment]
I can have a look at this.

**Comment by math1um** [comment]
Need to compute invariants and properties, then add name to graph_objects list
