### ISSUE TITLE
Conj.  independence_number(x) <= residue(x)^(degree_sum(x)^density(x)) is false

### ISSUE THREAD

**Issue by shivejl** [math1um/objects-invariants-properties#104]
Counterexample:

C_102

`'~?@ehCGGC@?G?_@?@??_?G?@??C??G??G??C??@???G???_??@???@????_???G???@????C????G????G????C????@?????G?????_????@?????@??????_?????G?????@??????C??????G??????G??????C??????@???????G???????_??????@???????@????????_???????G???????@????????C????????G????????G????????C????????@?????????G?????????_????????@?????????@??????????_?????????G?????????@??????????C??????????G??????????G??????????C??????????@???????????G???????????_??????????@???????????@????????????_???????????G???????????@????????????C????????????G????????????G????????????C????????????@?????????????G?????????????_????????????@?????????????@??????????????_?????????????G?????????????@??????????????C??????????????G??????????????G??????????????C??????????????@???????????????G???????????????_??????????????@???????????????@????????????????_???????????????G???????????????@????????????????E????????????????G'`

**Comment by rbarden** [comment]
added as graphs.CycleGraph(102)
