### ISSUE TITLE
Conj. independence_number(x) <= minimum(annihilation_number(x), 2*e^sum_temperatures(x)) is false

### ISSUE THREAD

**Issue by thenealon** [math1um/objects-invariants-properties#106]
CE:

```Graph('g??O?C_?`?@?O??A?A????????C?????G?????????A@aA??_???G??GA?@????????_???GHC???CG?_???@??_??OB?C?_??????_???G???C?O?????O??A??????G??')```

**Comment by rbarden** [comment]
Added.
