### ISSUE TITLE
add bi-clique property

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#11]
a *bi-clique* is a graph whose vertex set induces 2 disjoint cliques. a clique itself is an example of a bi-clique where all edges are present between the two cliques. 

these graphs have the property that residue=alpha. the value is 2, except in the case where all edges between the cliques are present, and the value is 1.

is there an efficient recognition algorithm?

**Comment by nvcleemp** [comment]
Isn't this equivalent to checking whether the complement is triangle-free? If the graph can't be partitioned into two cliques, then there are three vertices that form an independent set, so the complement contains a triangle.

**Comment by math1um** [comment]
>Isn't this equivalent to checking whether the complement is triangle-free?

hmmm. its certainly a necessary condition. i can't prove off-hand that its
a sufficient condition. but also can't think of a counterexample.

c

On Wed, May 4, 2016 at 11:52 AM, nvcleemp <notifications@github.com> wrote:

> Isn't this equivalent to checking whether the complement is triangle-free?
> If the graph can't be partitioned into two cliques, then there are three
> vertices that form an independent set, so the complement contains a
> triangle.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/math1um/objects-invariants-properties/issues/11#issuecomment-216909643>
>



-- 

CELarson Web: http://www.people.vcu.edu/~clarson

Automated Conjecturing for Sage: http://nvcleemp.github.io/conjecturing/

The Conjecturing Project: http://independencenumber.wordpress.com

VCU Discrete Math Seminar: http://www.people.vcu.edu/~dcranston/DM-seminar/

VCU Precalculus Web: http://wp.vcu.edu/precalculus

Craig Larson, Associate Professor
Department of Mathematics and Applied Mathematics
Virginia Commonwealth University

4106 Grace E. Harris Hall
1015 Floyd Avenue
Richmond, VA 23284-2014

**Comment by math1um** [comment]
c5 is a CE

On Wed, May 4, 2016 at 11:52 AM, nvcleemp <notifications@github.com> wrote:

> Isn't this equivalent to checking whether the complement is triangle-free?
> If the graph can't be partitioned into two cliques, then there are three
> vertices that form an independent set, so the complement contains a
> triangle.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/math1um/objects-invariants-properties/issues/11#issuecomment-216909643>
>



-- 

CELarson Web: http://www.people.vcu.edu/~clarson

Automated Conjecturing for Sage: http://nvcleemp.github.io/conjecturing/

The Conjecturing Project: http://independencenumber.wordpress.com

VCU Discrete Math Seminar: http://www.people.vcu.edu/~dcranston/DM-seminar/

VCU Precalculus Web: http://wp.vcu.edu/precalculus

Craig Larson, Associate Professor
Department of Mathematics and Applied Mathematics
Virginia Commonwealth University

4106 Grace E. Harris Hall
1015 Floyd Avenue
Richmond, VA 23284-2014

**Comment by math1um** [comment]
how about the complement is bipartite?

On Wed, May 4, 2016 at 11:52 AM, nvcleemp <notifications@github.com> wrote:

> Isn't this equivalent to checking whether the complement is triangle-free?
> If the graph can't be partitioned into two cliques, then there are three
> vertices that form an independent set, so the complement contains a
> triangle.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/math1um/objects-invariants-properties/issues/11#issuecomment-216909643>
>



-- 

CELarson Web: http://www.people.vcu.edu/~clarson

Automated Conjecturing for Sage: http://nvcleemp.github.io/conjecturing/

The Conjecturing Project: http://independencenumber.wordpress.com

VCU Discrete Math Seminar: http://www.people.vcu.edu/~dcranston/DM-seminar/

VCU Precalculus Web: http://wp.vcu.edu/precalculus

Craig Larson, Associate Professor
Department of Mathematics and Applied Mathematics
Virginia Commonwealth University

4106 Grace E. Harris Hall
1015 Floyd Avenue
Richmond, VA 23284-2014

**Comment by math1um** [comment]
yes, that's it.

**Comment by math1um** [comment]
defined is_biclique property in gt.sage

**Comment by nvcleemp** [comment]
This was added in 09d4264
