### ISSUE TITLE
add constructor for unique connected graph with max distinct_degrees

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#12]
there is a unique connected graph on n vertices with n-1 distinct degrees (n>2). call these _maximally irregular graphs_ (MIR_n)

MIR_2 is p2. MIR_4 is constructed from MIR_2 by joining all vertices to a new vertex v, and then adjoining a pendant to v. MIR_3 is p3. MIR_5 is constructed from MIR_3 by joining all vertices to a new vertex v, and then adjoining a pendant to v. 

in general MIR_(n+2) is constructed from MIR_n by joining all vertices to a new vertex v, and then adjoining a pendant to v (for n>3).

ryan pepper believes erdos discovered this construction.

**Comment by thenealon** [comment]
Is there a direct construction for this, rather than building MIR(n) recursively?

**Comment by rbarden** [comment]
Here's a bottom-up constructor that I came up with this afternoon. I did this after implementing a recursive version as well. They run in the same time (about .7sec when n=1000, iterative is slightly faster), but the iterative version doesn't run into a recursion depth issue. Python hits the maximum depth somewhere between 1000 and 2000 calls.
```python
def MIR(n):
    if n < 2:
        raise RuntimeError("MIR is defined for n >= 2")
    if n % 2 == 0:
        g = graphs.PathGraph(2)
    else:
        g = graphs.PathGraph(3)
    while g.order() < n:
        new_v = g.add_vertex()
        for v in g.vertices():
            g.add_edge(v, new_v)
        g.add_edge(new_v, g.add_vertex())
    return g
```

**Comment by rbarden** [comment]
Of course, it still runs in O(n³) time because of the inner for running more and more times on each loop of the outer while. But it's the best I can create right now.
