### ISSUE TITLE
Add Selkow's Independence Number lower bound

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#13]
See:
https://arxiv.org/abs/1705.03779

**Comment by wardbp** [comment]
For a graph g:

sum(1/(g.degree(v)+1) * (1 + max(g.degree(v)/(g.degree(v)+1) - sum(1/(g.degree(u)+1) for u in g.neighbors(v)),0)) for v in g.vertices())

**Comment by rbarden** [comment]
Closed by 83e8a64 in a duplicate issue, #288
