### ISSUE TITLE
Conj. independence_number(x) >= minimum(max_degree(x), floor(lovasz_theta(x))) is false

### ISSUE THREAD

**Issue by thenealon** [math1um/objects-invariants-properties#137]
CE:
```Graph('^?H{BDHqHosG??OkHOhE??B[CInU?@j_A?CoA^azGPLcb_@GEYYRPgG?K@gdPAg?d@_?_sGcED`@``O')```

**Comment by thenealon** [comment]
This should be double checked by somebody else; I'm still scared of lovasz_theta rounding errors (my counterexample finder doesn't use the preloaded database).

**Comment by rbarden** [comment]
```
alpha = 8
max_degree = 14
lovasz_theta = 9.0021733
```
I'd say the graph is good.
