### ISSUE TITLE
Conj. independence_number(x) >= minimum(floor(lovasz_theta(x)), tan(spanning_trees_count(x))) is false

### ISSUE THREAD

**Issue by thenealon** [math1um/objects-invariants-properties#138]
CE:  
```Graph('qWGh???BLQcAH`aBAGCScC@SoBAAFYAG?_T@@WOEBgRC`oSE`SG@IoRCK[_K@QaQq?c@?__G}ScHO{EcCa?K?o?E?@?C[F_@GpV?K_?_?CSW@D_OCr?b_XOag??C@gGOGh??QFoS?@OHDAKWIX_OBbHGOl??\Cb@?E`WehiP@IGAFC`GaCgC?JjQ???AGJgDJAGsdcqEA_a_q?')```

This should be doublechecked -- I'm not using the preloaded database, and I'm scared of lovasz rounding errors.

**Comment by rbarden** [comment]
```
alpha = 11
tan(spanning_trees_count) = 37.8974169261973
lovasz_theta = 12.089506
```
Looks good to me.
