### ISSUE TITLE
Add number of pendants as a graph invariant

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#14]
Test this with paths (value = 2), complete graphs and cycles (value = 0) and any trees in gt.sage

**Comment by wilcoxcookwn** [comment]
I'm on it.

**Comment by wilcoxcookwn** [comment]
```
def num_of_pendants(g):
	j = 0
	for v in g.vertices():
		if len(g.neighbors(v)) == 1:
			j += 1
	return j
```

This should work. Going to test shortly.

**Comment by harrisbm3** [comment]
I tested this and it seems to be correct

**Comment by rbarden** [comment]
When adding this, I found that the method already exists as card_pendants.
