### ISSUE TITLE
independence_number(x) >= floor(tan(barrus_bound(x) - 1)) is False

### ISSUE THREAD

**Issue by PratipRana** [math1um/objects-invariants-properties#141]
'RxCWGCB?G?_B?@??_?N??F??B_??w?'

**Comment by rbarden** [comment]
Please paste the graph into a code block. This string is invalid, probably due to markdown formatting on Github.

**Comment by PratipRana** [comment]
Graph('RxCWGCB?G?_B?@??_?N??F??B_??w?')

**Comment by PratipRana** [comment]
`Graph('RxCWGCB?G?_B?@??_?N??F??B_??w?')`
