### ISSUE TITLE
independence_number(x) >= floor(arccosh(lovasz_theta(x)))^2 is probably TRUE

### ISSUE THREAD

**Issue by PratipRana** [math1um/objects-invariants-properties#151]
We know independent_number(g)<=lovasz_theta(g). 
Replacing this (as arccosh is incresing fn) in independence_number(g) >= floor(arccosh(independent_number(g)))^2
or, 0>= floor(arccosh(independent_number(g)))^2 -independence_number(g)
Now if independent number is 4 this function is 0. Otherwise its always -ve.

**Comment by thenealon** [comment]
I agree that independence_number(g) >= floor(arccosh(independent_number(g)))^2 -- but as you say, floor(arccosh(x))^2 is non-decreasing, and so when you replace independence_number(g) with lovasz_theta(g), the right hand side of your inequality may _increase_.

(Of course, it is also possible that I'm missing the point, so...)

**Comment by PratipRana** [comment]
Yes sir.  That's what it's not the complete prove. But arccosh is very slowly growing function when x is high. I have plotted this function for x-->(0,100). And it looks like this conj. is true. Of course, we need to prove it.

**Comment by rbarden** [comment]
Closed by accident

**Comment by thenealon** [comment]
This conjecture is false; CE:
```Graph('~?@Td|wi\\fbna~}wepkkbXcrW}\\~NvtLKpY\\J_Ub^~yM~^tHnM}jPffKkqnijvxD@xa{UOzzvr?L^PFi||yt@OQ\YU{Vh]tWzwzpj\\n|kR]`Y}RpCvxk{rEMRP\\}|}dNdNtbO~yrkgMxlOXr|FvQ{tvfKKnHrp^}jV\\B^n\\LvLZeyX}QSKN^sm~yl\\[NJZXqdk]O|^zHl~vC{w`Nsn}x]utqrJozKXV|eIUUPv~ydc}]xJNWZjW|lpYm}{Jf~JWMixb^t]e|S~B[vKc{K[Kjut~}Kj~iAl\\tVNgyZadvoA}rdTlr\\\\wNr^^kJzrp|qlVy]siKncI~`oNm|ul\\PxDRyzddDzrjUn~ciOgbR}p~Cz|~MlxYoEVnVuZkxJgvmtE]]}~PRp[He]oBQz]PVJ~gVnvSUR|QF|`lomFh[j|jIaS~vh~_rYiiK}FnEW}ovnntxtRFBakzvwn[biJhNvf|VDV?m~Y]ndmfJQ|M@QvnNf~MCyn~{HSU~fvEv~@}u|spOXzTVNY\\kjDNt\\zRMXxU|g|XrzFzDYiVvho}bQbyfI{{w[_~nrm}J~LhwH}TNmfM^}jqajl_ChY]M}unRK\\~ku')```
