### ISSUE TITLE
Gosil eigenvalue bounds for independence number

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#16]
See the attached 2008 paper. Are there any bounds here for non-regular graphs? In the Laplacian matrix built-in to Sage? Are there example in the paper to test that your code is correct?
[godsil-newman-eigenvalue-bounds-independence-2008.pdf](https://github.com/math1um/objects-invariants-properties/files/1028337/godsil-newman-eigenvalue-bounds-independence-2008.pdf)

**Comment by wilcoxcookwn** [comment]
The Laplacian matrix is built into sage. I'll have a go at this.

**Comment by rbarden** [comment]
Closed by c50b5dc in duplicate issue #217
