### ISSUE TITLE
Add Double Fork Graph from Rebennack Paper

### ISSUE THREAD

**Issue by alf3x** [math1um/objects-invariants-properties#187]
Double Fork: `'E?dg'`
p.185
Rebennack, Steffen, Gerhard Reinelt, and Panos M. Pardalos. "A tutorial on branch and cut algorithms for the maximum stable set problem." International Transactions in Operational Research 19.1-2 (2012): 161-199.

**Comment by rbarden** [comment]
Closed by 3707964
