### ISSUE TITLE
Add Staton triangle-free bound

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#188]
from:
Staton, William. "Some Ramsey-type numbers and the independence ratio." Transactions of the American Mathematical Society 256 (1979): 353-370.

For a triangle-free graph with maximum degree > 2, alpha >= 5n/(5*Delta-1), where n=order and Delta=max_degree

To make this an invariant for *any* graph, you can test for triangle-freeness of the input graph and give 1 for graphs with a triangle  or max_degree < 3, and  5n/(5*Delta-1) for triangle-free graphs

Testing for triangle-freeness is efficient and built in: Graph.is_triangle_free

**Comment by math1um** [comment]
Staton paper attached.
[staton-independence-ratio-1979.pdf](https://github.com/math1um/objects-invariants-properties/files/1055510/staton-independence-ratio-1979.pdf)

**Comment by alf3x** [comment]
As an Invariant:
```
def Staton_triangle_free_bound_inv(g):
    if (g.is_triangle_free() and max(g.degree()) >= 3):
        bound = (5*g.order())/(max(g.degree()) - 1)
    else:
        bound = 1
    return bound
```
As a Theorem:
```
def Staton_triangle_free_bound_thm(g):
    if (g.is_triangle_free() and max(g.degree()) >= 3):
        boolean = independence_number(g) >= (5*g.order())/(max(g.degree()) - 1)
        return boolean
    else:
        return True
```
