### ISSUE TITLE
Open Conjecture: alpha >= ceil(lovasz_theta) - girth

### ISSUE THREAD

**Issue by wardbp** [math1um/objects-invariants-properties#191]
Haven't been able to find a CE to this one yet

**Comment by cjoshea9** [comment]
Conjecture works for all connected graphs with less than or equal to 8 vertices

**Comment by cjoshea9** [comment]
This conjecture works for random graphs with 20 to 60 vertices. (I tested 1000 graphs with 20 vertices, 21 vertices, 22 vertices, etc.)

**Comment by a234** [comment]
The Paley graph of order 101 is a counterexample.
