### ISSUE TITLE
Add Harant lower bound for alpha

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#192]
See Thm 5, p. 240 of attached.
alpha >= (CW^2)/(CW - sum(d_i-d_j)^2*q_i^2*q_j^2)
where d_i is the degree of vertex v_i, the sum is over all edges v_i-v_j and q_i=1/(d_i+1) and CW is the Caro-Wei lower bound for alpha, CW = sum(q_i)

CW and Harant are efficiently computable and Harant can also be added an an invariant.
[harant-independence-number-lower-bound-1998.pdf](https://github.com/math1um/objects-invariants-properties/files/1055644/harant-independence-number-lower-bound-1998.pdf)

**Comment by rbarden** [comment]
Just to make clear the bound:
alpha >= (CW^2) / (CW - sum(d_i-d_j)^2 * q_i^2 * q_j^2)
