### ISSUE TITLE
Add brooks alpha lower bound theorem to gt.sage

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#193]
It follows from alpha*chromatic_number >= n, and the Brooks bound (included in any graph theory text) for chromatic number that:
alpha >= n/brooks

This lower bound might be usefully added as brooks_alpha_lower_bound_thm to gt.sage and computed for the db, etc

**Comment by math1um** [comment]
We should add a brooks_alpha_bound invariant too

and it should be ceil(n/brooks) as alpha is an integer we can always round up.

**Comment by rbarden** [comment]
Theorem added in b525febbe286f9b8ab0246f98d7f08f8c3f2f567
