### ISSUE TITLE
Include documentation and doctests for (all) invariants, properties and objects

### ISSUE THREAD

**Issue by nvcleemp** [math1um/objects-invariants-properties#2]
At the moment several methods have no documentation or only a short line of comment describing what they do. Ideally, we transform all of these into docstrings, so that the information is visible from within Sage. We can also include doctests at the same time.

**Comment by nvcleemp** [comment]
This effort was already started in 2804b7c, 58613a6, 976bfd1 and 4adc085.

**Comment by yirkajk** [comment]
Closing this in favor of a new/updated issue regarding documentation
