### ISSUE TITLE
Add examples of graphs with n-1 distinct degrees

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#20]
It has been claimed that there is a unique connected graph on n vertices with n-1 distinct degrees (the triangle+pendant graph on 4 vertices is an example). Can you prove this?

We should code some more examples of higher order. Give them good names. Write a doctest that confirms this "irregularity" property.

**Comment by PratipRana** [comment]
is the order of 6/8 will be fine?

**Comment by PratipRana** [comment]
able to build a program which will generate this for n vertex. (though n is even here, possibly for odd vertex order this is not possible)

**Comment by nvcleemp** [comment]
For odd order you can start from a path with 3 vertices.

**Comment by rbarden** [comment]
The constructor for these graphs is given in issue #12 . I have not seen a proof that only one exists per order, but I have seen references to this being the case.

**Comment by rbarden** [comment]
> Maximum Size of Maximally Irregular Graphs 
> by 
> Batmend Horoldagva, Lkhagva Buyantogtokh, Shiikhar Dorjsembe, Ivan Gutman

cites

> M. Behzad, G. Chartrand, No graph is perfect, Am. Math. Monthly 74 (1967)
> 962–963.

> For each n > 1, there is a unique connected
> quasi–perfect graph of order n and its degree sequence is
> [
> n − 1, n − 2, . . . , ⌊n/2⌋, ⌊n/2⌋, . . . , 2, 1
> ]
>
