### ISSUE TITLE
Godsil-Newman alpha upper bound

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#217]
alpha <= n*(lambda_1-delta)/lambda_1

where n=order, lambda_1 = largest_eigenvalue, delta = min_degree

see (attached):
Godsil, Chris D., and Mike W. Newman. "Eigenvalue bounds for independent sets." Journal of Combinatorial Theory, Series B 98.4 (2008): 721-734.
[godsil-newman-eigenvalue-bounds-independence-2008.pdf](https://github.com/math1um/objects-invariants-properties/files/1058599/godsil-newman-eigenvalue-bounds-independence-2008.pdf)

this same bound was proved independently by Lu-Liu-Tian

**Comment by shivejl** [comment]
```
def Godsil_Newman_UB(g):
    L = max(g.laplacian_matrix().change_ring(RDF).eigenvalues())
    return g.order()*(L-min_degree(g))/L
```
