### ISSUE TITLE
Harant-Henning-Rautenbach-Schiermeyer alpha lower bound  

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#218]
This bound is for K4-free sub-cubic graphs. Define it as 1 for graphs which are not K4-free or not sub-cubic (each of which can be tested efficiently).

Thm. For a connected graph,
alpha >= (4n-m-lambda-tr)/7

where n=order, m=size, tr=max number of vertex-disjoint triangles, lambda=0 if it is *bad*, and 1 if it is not.

A graph is *bad* is it has a *difficult* block. A block is difficult if it is isomorphic to k3, c5, k4*, or c5* (see picture on p.5830).

NOTE: tr can be computed efficiently (p.5830). tr(G) = "the number of non-trivial components of the graph formed by the edges of G which lie in a triangle of G".

Call it HHRS and define it both as a theorem and invariant.

See (attached):
Harant, Jochen, et al. "The independence number in graphs of maximum degree three." Discrete Mathematics 308.23 (2008): 5829-5833.
[harant-et-al-independence-number-max-degree-three-2008.pdf](https://github.com/math1um/objects-invariants-properties/files/1058777/harant-et-al-independence-number-max-degree-three-2008.pdf)

**Comment by alf3x** [comment]
As a Theorem:
```
def HHRS_thm(g):
    n = g.order()
    m = g.size()
    tr_ = tr(g)
    if (is_bad(g)):
        lambda_ = 0
    else:
        lambda_ = 1
    return independence_number(g)>= ((4 * n) - m - lambda_ - tr_)/7
```
As an Invariant:
```
def HHRS_inv(g):
    n = g.order()
    m = g.size()
    tr_ = tr(g)
    if (is_bad(g)):
        lambda_ = 0
    else:
        lambda_ = 1
    return ((4 * n) - m - lambda_ - tr_)/7
```

**Comment by nvcleemp** [comment]
Another way to implement the theory version is

```
def HHRS_thm(g):
    return independence_number(g)>= HHRS_inv(g)
```

This has the advantage that if we find a more efficient way to compute the invariant, or we find that there is a mistake in the invariant, we only need to change it in one location.

**Comment by rbarden** [comment]
The paper states:
> For a graph G we denote by λ(G) the number of components of G which are bad...
which is opposite what is written in the original issue.
