### ISSUE TITLE
Add tr invariant

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#219]
tr=max number of vertex-disjoint triangles.

NOTE: tr can be computed efficiently (p.5830). tr(G) = "the number of non-trivial components of the graph formed by the edges of G which lie in a triangle of G".

See:
Harant, Jochen, et al. "The independence number in graphs of maximum degree three." Discrete Mathematics 308.23 (2008): 5829-5833.

**Comment by alf3x** [comment]
```
def tr(g):
    aux_g = form_triangles_graph(g)
    return independence_number(aux_g)
```
