### ISSUE TITLE
Add is_bad graph property

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#220]
A graph is bad is it has a difficult block. A block is difficult if it is isomorphic to k3, c5, k4*, or c5* (see picture on p.5830).

See:
Harant, Jochen, et al. "The independence number in graphs of maximum degree three." Discrete Mathematics 308.23 (2008): 5829-5833.

**Comment by alf3x** [comment]
```
def is_bad(g):
    k3 = graphs.CompleteGraph(3)
    k4 = graphs.CompleteGraph(4)
    c5 = graphs.CycleGraph(5)
    if (g.is_isomorphic(k3) or g.is_isomorphic(k4) or g.is_isomorphic(c5)):
        return True
    else:
        return False
```

**Comment by thenealon** [comment]
Don't commit yet -- this property is somewhat more complicated.  A _block_ in a graph has a specific definition (it is a maximal connected subgraph with no cut vertex). So this is progress, but we need to first break a graph into its blocks and then use the above code to check if each block is one of the forbidden subgraphs.  (This is also missing k4* and c5*)

**Comment by rbarden** [comment]
Yeah I noticed this yesterday and was going to bring it up this morning.

**Comment by alf3x** [comment]
```
def is_bad(g):
    k3 = graphs.CompleteGraph(3)
    k4_ = Graph('GhcGKc')
    c5 = graphs.CycleGraph(5)
    c5_ = Graph('Ehdo')
    blocks = g.blocks_and_cut_vertices()[0]
    #To make a subgraph of g from the ith block
    for i in blocks:
        h = g.subgraph(i)
        boolean = h.is_isomorphic(k3) or h.is_isomorphic(k4_) or h.is_isomorphic(c5) or h.is_isomorphic(c5_)
        if boolean == True:
            return True
    return False
```
How does this look now?
