### ISSUE TITLE
Add an anti-hole generator

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#23]
A "hole" in a graph is a cycle of size at least 5. An "anti-hole" is the complement of a hole. 

Code an anti-hole generator: a function that produces complements of cycles, maybe anti_hole(n). Add a few of these and names to gt.sage.

**Comment by wilcoxcookwn** [comment]
def antihole(n):
	return complement(graphs.CycleGraph(n))
This should be sufficient, should be ready to be checked.
