### ISSUE TITLE
Add Lemke Graph

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#24]
See:
http://www.people.vcu.edu/~ghurlbert/pebbling/pnummain.html

Remember to give it a name.

**Comment by math1um** [comment]
This a test! You can add a comment similarly!

**Comment by rbarden** [comment]
I got `G_?ztw`. Can someone else confirm one or the other?

**Comment by thenealon** [comment]
These are non-isomorphic; 'G_?ztw' is the Lemke. (check: the Lemke graph has a degree 4 vertex adjacent to a degree 2 vertex)

**Comment by rbarden** [comment]
Added.
