### ISSUE TITLE
Add Circular Graph from Brimkov Paper

### ISSUE THREAD

**Issue by alf3x** [math1um/objects-invariants-properties#249]
C(13,2): `'LQGOOGA?O@OAOA'`
p.1814
Brimkov, Valentin. "Algorithmic and explicit determination of the Lovasz number for certain circulant graphs." Discrete Applied Mathematics 155.14 (2007): 1812-1825.

**Comment by rbarden** [comment]
This graph is a circulant graph that contains extra edges on top of the cycle given.

**Comment by math1um** [comment]
Brimkov 2007 attached
[brimkov-lovasz-number-for-circulant-graphs-2007.pdf](https://github.com/math1um/objects-invariants-properties/files/1174173/brimkov-lovasz-number-for-circulant-graphs-2007.pdf)
