### ISSUE TITLE
Add independence_ratio invariant to gt.sage

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#255]
independence_number/order

this was widely studied in the 70s and 80s. while each invariant is included separately, and this can be formed by the program, in a sense it makes it "easier" for the program to make conjectures involving this invariant.

this is NP-hard-to-compute and should be included in the hard-to-compute invariants list. it will be easy to precompute these though - from the already computed database for independence number.

**Comment by thenealon** [comment]
```
def independence_ratio(g):
    return independence_number(g)/(g.order()+0.0)
```
