### ISSUE TITLE
Add depth invariant to gt.sage

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#257]
depth = order-residue

this is the number of steps it takes for Havel-Hakimi to terminate. fajtlowicz defined this as its efficiently computable.

while each invariant is included separately, and this can be formed by the program, in a sense it makes it "easier" for the program to make conjectures involving this invariant.

**Comment by thenealon** [comment]
```
def depth(g):
    return g.order()-residue(g)
```
