### ISSUE TITLE
Add is_quasi_regular property to gt.sage

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#260]
A graph is *regular* is all degrees are the same. A graph is *quasi regular* if the maximum degree and the minimum degree differ by at most one. (So there are either 1 or 2 different degrees, and this class includes regular graphs).

See (attached):
Favaron, Odile, Maryvonne Mahéo, and J‐F. Saclé. "On the residue of a graph." Journal of Graph Theory 15.1 (1991): 39-64.
[favaron-maheo-sacle-residue-1991.pdf](https://github.com/math1um/objects-invariants-properties/files/1061301/favaron-maheo-sacle-residue-1991.pdf)

**Comment by thenealon** [comment]
I'll do this.

```
def is_quasi_regular(g):
    if maximum_degree(g)-minimum<2:
        return true
    return false
