### ISSUE TITLE
Add Harant-Schiermeyer alpha lower bound

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#262]
alpha >= [(2m+n+1)-sqrt((2m+n+1)^2-4n^2)]/2

this should be added as a theorem. the RHS should be added as an invariant

see (attached):
Harant, Jochen, and Ingo Schiermeyer. "On the independence number of a graph in terms of order and size." Discrete Mathematics 232.1-3 (2001): 131-138.
[harant-schiermeyer-independence-order-size-2001.pdf](https://github.com/math1um/objects-invariants-properties/files/1061343/harant-schiermeyer-independence-order-size-2001.pdf)

**Comment by alf3x** [comment]
As a Theorem:
```
def Harant_Schiermeyer_alpha_lower_bound_thm(g):
    return independence_number(g) >= [(2*g.size() + g.order() + 1) -sqrt((2*g.size() + g.order() + 1)^2 - 4*g.order()^2)]/2
```
As an Invariant:
```
def Harant_Schiermeyer_alpha_lower_bound_inv(g):
    return ((2*g.size() + g.order() + 1) -sqrt((2*g.size() + g.order() + 1)^2 - 4*g.order()^2))/2
```
