### ISSUE TITLE
Shearer odd girth alpha lower bound 

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#274]
First find the girth. This is efficiently computable. see, for instance:
https://webcourse.cs.technion.ac.il/234247/Winter2003-2004/ho/WCFiles/Girth.pdf

If the girth is even, let shearer_odd_girth_alpha_bound = 1.

Thm. For a graph with odd girth 2k+1,
alpha >= 2^-((k-1)/k)*[sum(d(v)^(1/(k-1))]^((k-1)/k)
where the sum is over all vertices, and d(v) is the degree of vertex v.

See (attached):
Shearer, James B. "The independence number of dense graphs with large odd girth." Electron. J. Combin 2.2 (1995).
[shearer-independence-odd-girth-1995.pdf](https://github.com/math1um/objects-invariants-properties/files/1061422/shearer-independence-odd-girth-1995.pdf)

**Comment by alf3x** [comment]
```
def Shearer_odd_girth_alpha_lower_bound_inv(g):
    if g.girth() == +Infinity:
        return 1
    if (is_even(g.girth())):
        bound = 1
    else:
        k = ((g.girth() - 1)/2.0)
        v_sum = sum([g.degree(v)^(1/(((g.girth() - 1)/2.0)-1.0)) for v in g.vertices()])
        bound = 2^(-(k -1)/k)*v_sum^((k-1.0)/k)
    return bound
```
