### ISSUE TITLE
Add Seklow alpha lower bound

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#288]
Thm. alpha >=
sum[(1/(d(v)-1)*(1+max(0,(d(v)/(d(v)+1)-sum(1(d(w)+1)))],
where the fist sum goes over all vertices v, and the second sum goes over all the neighbors w of v.

This, and all other obscure-looking formulas, should be *tested* for their truth against the graphs in graph_objects at least.

The seklow_alpha_lower_bound 

See (attached);
Selkow, Stanley M. "A probabilistic lower bound on the independence number of graphs." Discrete Mathematics 132.1-3 (1994): 363-365.
[seklow-probabailistic-lower-bound-alpha-1994.pdf](https://github.com/math1um/objects-invariants-properties/files/1064133/seklow-probabailistic-lower-bound-alpha-1994.pdf)

**Comment by alf3x** [comment]
It looks like the first summand should be sum[(1/(d(v)+1)
Is this a typo?

**Comment by alf3x** [comment]
```
def Seklow_alpha_lower_bound_thm(g):
    truth_value = True
    v_sum = 0
    for v in g.vertices():
        w_sum = sum([(1/(g.degree(w) + 1)) for w in g.neighbors(v)])
        v_sum += sum((1/(g.degree(v) + 1))*(1 + max(0,(g.degree(v)/(g.degree(v) + 1) - w_sum))))
    if independence_number(g) < v_sum:
        truth_value = False
    return truth_value
```

**Comment by alf3x** [comment]
This code returns True for all graphs in graph_objects
