### ISSUE TITLE
Add max_even invariant

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#289]
For a given vertex v, find the number of vertices at even distance from v (v is distance 0 from itself, so include that too).  (For a bipartite graph this will be an independent set). Then return the max over all vertices.

Also add min_even invariant.

**Comment by wardbp** [comment]
for a graph g

def max_even(g):
    max = 0
    for v in g.vertices():
        evens = 0
        for u in g.vertices():
            if g.distance(v,u)%2 == 0:
                evens += 1
        if evens > max:
            max = evens
    return max

**Comment by nvcleemp** [comment]
For each pair of vertices this computes the distance twice. I don't know how well the results are cached in Sage, but a better way might be to use the distance matrix. Computing all distances at once is cheaper than computing each distance separately.

See http://doc.sagemath.org/html/en/reference/graphs/sage/graphs/distances_all_pairs.html#sage.graphs.distances_all_pairs.distances_all_pairs for more details.

**Comment by rbarden** [comment]
How do these look? Efficiency of searching through the double dictionary is O(n²) but I can't think of any way to make it better.
```
def max_even(g):
    from sage.graphs.distances_all_pairs import distances_all_pairs
    D = distances_all_pairs(g)
    evens_list = []
    for u in D:
        evens = 0
        for v in D[u]:
            if D[u][v] % 2 == 0:
                evens += 1
        evens_list.append(evens)
    return max(evens_list)
```
```
def min_even(g):
    from sage.graphs.distances_all_pairs import distances_all_pairs
    D = distances_all_pairs(g)
    evens_list = []
    for u in D:
        evens = 0
        for v in D[u]:
            if D[u][v] % 2 == 0:
                evens += 1
        evens_list.append(evens)
    return min(evens_list)
```

**Comment by nvcleemp** [comment]
I think this will be fine. There might  some ways that are asymptotically slightly better, but they have a much higher initial overhead, so for any practical graph, this will be the best we can do.
