### ISSUE TITLE
add pepper residue graph

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#3]
Residue is NOT monotone. Here is example. Take K3 and attach a pendant to each vertex. Copy this graph. Add a vertex and join it to all of the 6 pendants. Degree sequence is now {6,3,3,3,3,3,3,1,1,1,1,1,1} and this has residue of 4. Remove the central added vertex of degree 6 and you get a graph (disjoint in this case) whose degree sequence is {3,3,3,3,3,3,1,1,1,1,1,1} and this has residue of 5. Thus, R(G-v) > R(G) 

from Ryan Pepper 5-Apr-2016

**Comment by nvcleemp** [comment]
Clearly the degree sequence has to contains twos and not ones. :wink:

**Comment by nvcleemp** [comment]
The graph is now in `gt.sage`, but the invariants and properties still need to be calculated before adding it to the list.

**Comment by nvcleemp** [comment]
This graph was added to the list in 9519e1a
