### ISSUE TITLE
Add bipartite_number invariant

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#307]
This is the largest number of vertices that induces a bipartite subgraph.

This is almost certainly hard to compute - and should be added to the hard invariants list. Naively, you can look at *every* subset of vertices and find the largest one that induces a bipartite sugraph (testing for bipartiteness is efficient - and there is an is_bipartite graph method). 

Maybe you can imitate the Tarjan-Trojanowski idea: a given vertex is either in a maximum bipartite subgraph - or it is not - in the case that you do include a vertex v you can then eliminate the neighbors of v that would induce an odd cycle with the other vertices you've included (a graph is bipartite iff there are no odd cycles).

**Comment by cjoshea9** [comment]
Working code for the bipartite_number. Testing completed

`def bipartite_number(g):
    """
    Defined as the largest number of vertices that induces a bipartite subgraph
    
    sage: bipartite_number(pete)
    7
    sage: bipartite_number(c4)
    4
    sage: bipartite_number(k3)
    2
    """
    
    set_of_subsets = Set(g.vertices()).subsets()
    
    verts = 0
    
    for x in set_of_subsets:
        h = g.subgraph(list(x))
        if h.is_bipartite():
            if h.order() > verts:
                verts = h.order()
    
    return verts`

**Comment by rbarden** [comment]
I'll close it with the enhancement label as a note to come back to it to see if it can't be made a bit more efficient.
