### ISSUE TITLE
Graph from Willis' thesis p.10, Fig. 2.2

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#31]
Please add a note for what;'s special about this graph.

**Comment by shivejl** [comment]
Feel free to check:

'IsP@OkWHG'

This is a graph for which the Cvetkovic Bound gives a better estimate for alpha than any of the other upper bounds (alpha=4, n=10, e=15, p0=0, p_=4, p+=6, Delta=3, delta=3). Also, House of Graphs says this is isomorphic to the Petersen Graph.

**Comment by rbarden** [comment]
Since it is isomorphic to the Petersen Graph, I won't add it.
