### ISSUE TITLE
AGX alpha upper bound

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#330]
Thm (p.2531):
alpha <= n + Delta - ceil(2*sqrt(n-1)),
where n=order, and Delta=max_degree

Is this theorem of practical use (does it give a better value for any specific graph G than other known bounds)?

This can be added as a theorem as well as an invariant: AGX_alpha_upper_bound

See (attached):
Aouchiche, Mustapha, Gunnar Brinkmann, and Pierre Hansen. "Variable neighborhood search for extremal graphs. 21. Conjectures and results about the independence number." Discrete Applied Mathematics 156.13 (2008): 2530-2542.
[auchiche-favaron-hansen-VNS-AGX-independence-22-2009.pdf](https://github.com/math1um/objects-invariants-properties/files/1064595/auchiche-favaron-hansen-VNS-AGX-independence-22-2009.pdf)

**Comment by shivejl** [comment]
As a theorem:
```
def AGX_alpha_upper_bound_thm(g):
    return independence_number(g) <= g.order() + max_degree(g) - ceil(2*sqrt(g.order()-1))
```

As an invariant:
```
def AGX_alpha_upper_bound_inv(g):
    return g.order() + max_degree(g) - ceil(2*sqrt(g.order()-1))
```
