### ISSUE TITLE
Conj. independence_number(x) >= -brinkmann_steffen(x) - girth(x) + matching_number(x) is false

### ISSUE THREAD

**Issue by thenealon** [math1um/objects-invariants-properties#335]
CE:
```Graph('~?@VNtyzkW^v~_?UMVuzfYa_~}|tWZ}v~~v}WgheAI[pTRjr\Wv}y~VeypzF\^zmq}C\UFoD^XJFQwvU^AovUND~XnF]STE_EF~v^~~JF\X{X\VFoeMvmy~xzZv\^{|n~v~~~^v}y~xz]Wihy_Lzmq]CxSawvUNFZr]zj~fl|vMy~wz^Z}q}MxvsZv\^{|nnuMy~wr^\vmy~xz^^z~\^}|nny{qUMHRpZSSE_EC_A@VXJAShyGe|vV~NZz~i}vUNnZr~n]zj~fl|vr^u~p~~}~~z}v}N~~v~~nzNwzf^\n~TuQodI]AHvuMy^wr^\wkNz^w~|~^}~y}vUNNZr~n~v}y~|z^^|~~^zn~~n~~v~y}q]MxVtZn|y{qUMHRpZfx|WyhIbL|vap[~}~~~~~~~~~}|vV~NZz~fz~jzHWydNDmzvz~~~~~~~~~~~~c?AGgA]Kw_PC_?_???O?????V~v~~~^~~n~~}\uRofIca@FHcd~z~N~~~~~~~}Zaw}?oscOOx?d}ptR|EZznDbxsj~z~~~~~~~~~}^cAAYgA^KwgPCc]~v^~~^~~n~~}znz\w~|~^}~~~r|v}y~|z^^|~~~t^Vuyp|z]^|~~~dZz~\^{|nn}~~~ynw')```

**Comment by rbarden** [comment]
This graph string raises a runtime error, says that it contains at least one invalid character.

**Comment by thenealon** [comment]
This is the same \ vs. \\ error. The correct g6 string is:
```g=Graph('~?@VNtyzkW^v~_?UMVuzfYa_~}|tWZ}v~~v}WgheAI[pTRjr\\Wv}y~VeypzF\\^zmq}C\\UFoD^XJFQwvU^AovUND~XnF]STE_EF~v^~~JF\\X{X\\VFoeMvmy~xzZv\\^{|n~v~~~^v}y~xz]Wihy_Lzmq]CxSawvUNFZr]zj~fl|vMy~wz^Z}q}MxvsZv\\^{|nnuMy~wr^\\vmy~xz^^z~\\^}|nny{qUMHRpZSSE_EC_A@VXJAShyGe|vV~NZz~i}vUNnZr~n]zj~fl|vr^u~p~~}~~z}v}N~~v~~nzNwzf^\\n~TuQodI]AHvuMy^wr^\\wkNz^w~|~^}~y}vUNNZr~n~v}y~|z^^|~~^zn~~n~~v~y}q]MxVtZn|y{qUMHRpZfx|WyhIbL|vap[~}~~~~~~~~~}|vV~NZz~fz~jzHWydNDmzvz~~~~~~~~~~~~c?AGgA]Kw_PC_?_???O?????V~v~~~^~~n~~}\\uRofIca@FHcd~z~N~~~~~~~}Zaw}?oscOOx?d}ptR|EZznDbxsj~z~~~~~~~~~}^cAAYgA^KwgPCc]~v^~~^~~n~~}znz\\w~|~^}~~~r|v}y~|z^^|~~~t^Vuyp|z]^|~~~dZz~\\^{|nn}~~~ynw')```

**Comment by rbarden** [comment]
Thanks!
