### ISSUE TITLE
Conj. independence_number(x) <= minimum(size(x), 10^laplacian_energy(x)) is false

### ISSUE THREAD

**Issue by thenealon** [math1um/objects-invariants-properties#338]
CE:
```Graph('b????????????????????~~|~~|}~x~n~vp~{Nz{^e~svN}Xc~zFKZ~uyX[z[J\ti@M~mT@]}X{SzQZQQ^posGNlZg?R}lp`LX{L?')```

**Comment by rbarden** [comment]
This graph string raises a runtime error, says that it contains at least one invalid character.

**Comment by thenealon** [comment]
Hi,

These can be fixed easily by replacing every appearance of "\" with "\\". So, the corrected graph is:

```
Graph('b????????????????????~~|~~|}~x~n~vp~{Nz{^e~svN}Xc~zFKZ~uyX[z[J\\ti@M~mT@]}X{SzQZQQ^posGNlZg?R}lp`LX{L?')
```

**Comment by rbarden** [comment]
Thanks Dr. Bushaw
