### ISSUE TITLE
Add lovasz_theta_over_root_n invariant

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#347]
lovasz_theta(G)/sqrt(n),
where n= order of G

it is conjectured there is a constant c such that lovasz_theta(G)/c*sqrt(n) <= alpha,
for all graphs

from p.45 of Knuth paper:
http://www.combinatorics.org/ojs/index.php/eljc/article/view/v1i1a1

**Comment by thenealon** [comment]
Just to clarify, this is lovasz_theta(G)/(c*sqrt(n)) <= alpha, or lovasz_theta<=c*alpha*sqrt(n).

**Comment by thenealon** [comment]
We need to be careful, everybody, and test our functions -- this was committed in non-running form, missing a set of parentheses.

**Comment by rbarden** [comment]
Thank you. When loaded, it didn't throw an error but should work properly now.
