### ISSUE TITLE
Add two_stability_theta_bound invariant

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#349]
Let two_stability_theta_bound(G) = 2^(2/3)*n^(1/3),
where n = order.

For graphs with alpha<=2,
lovasz_theta <= 2^(2/3)*n^(1/3)

from p.47 of Knuth paper:
http://www.combinatorics.org/ojs/index.php/eljc/article/view/v1i1a1

**Comment by thenealon** [comment]
```
def two_stability_theta(g):
    return 2^(2/3)*g.order()^(1/3)
```
