### ISSUE TITLE
Add transmission invariant to gt.sage

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#357]
The *transmission* is the sum of all distances between pairs of vertices of a connected graph.

This will be efficiently compuatable, and there is a relevant built-in Sage Graph method that gives "all distances".
 
See (attached):
Plesník, Ján. "On the sum of all distances in a graph or digraph." Journal of Graph Theory 8.1 (1984): 1-21.
[plesnik-sum-of-distances-1984.pdf](https://github.com/math1um/objects-invariants-properties/files/1077877/plesnik-sum-of-distances-1984.pdf)

**Comment by thenealon** [comment]
Average distance is already in GT.sage, so this can be coded as average_distance(g)*n*(n-1), where n is the order of the graph.

**Comment by thenealon** [comment]
```
def transmission(g):
    n=g.order()
    return average_distance(g)*n*(n-1)
```

**Comment by math1um** [comment]
This seems like it might introduce numerical error, when the answer is an integer. Please check that Sage gives integers for at least the graphs in graph_objects

**Comment by rbarden** [comment]
It does produce an integer for all graphs in the current list.

**Comment by rbarden** [comment]
Just to be ever so slightly more efficient, I wrote it the same as average distance without the final division at the end. This removes the method call and the unnecessary arithmetic operations.
