### ISSUE TITLE
Add graph from Willis thesis' p.18, fig. 2.9

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#36]
Please add a note for what;'s special about this graph.

**Comment by shivejl** [comment]
I'll take this.

**Comment by shivejl** [comment]
Feel free to check:

'E}lw'

This is a graph for which the Minimum Degree Bound gives a better estimate for alpha than any of the other upper bounds (alpha=2, n=6, e=12, p0=3, p_=2, p+=1, Delta=4, delta=4)

**Comment by rbarden** [comment]
I got 'E`~o'. Can someone else confirm this?

**Comment by harrisbm3** [comment]
I believe Graph('E}lw') is correct.

in Graph('E`~o') every vertex has has degree of 3 where the graph needed ever vertex has degree of 4. I also recreated the graph to confirm.

**Comment by rbarden** [comment]
Thanks @harrisbm3, added.
