### ISSUE TITLE
Add harmonic_index graph invariant

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#362]
harmonic_index = the sum, over all edges vw, of 2/(d(v)+d(w)), where d(v) is the degree of vertex v.

See:
http://www.sciencedirect.com/science/article/pii/S089396591100471X

**Comment by cjoshea9** [comment]
`def harmonic_index(g):
    sum = 0
    for edge in g.edges(labels = false):
        v = edge[0]
        w = edge[1]
        sum += 2 / (g.degree()[v] + g.degree()[w])
        
    return sum`

Working code for the harmonic_index invariant 
Testing done

**Comment by cjoshea9** [comment]
def harmonic_index(g):
    sum = 0
    for edge in g.edges(labels = false):
        v = edge[0]
        w = edge[1]
        sum += 2 / (g.degree()[v] + g.degree()[w])
        
    return sum

Working code for the harmonic_index
Testing done

**Comment by cjoshea9** [comment]
`def harmonic_index(g):
    sum = 0
    for edge in g.edges(labels = false):
        v = edge[0]
        w = edge[1]
        sum += 2 / (g.degree()[v] + g.degree()[w])
    return sum`

Working code for the harmonic_index invariant
