### ISSUE TITLE
Add min_degree_of_vertex_in_max_ind_set invariant

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#364]
The naive algorithm:
Find all maximum independent sets, find the minimum degree of any of these vertices.

This concept shows up in the proof of:
alpha <= n - min_degree

and could be used in investigating automated proof sketches.

Include it as a "hard" invariant.

**Comment by cjoshea9** [comment]
Working code for this invariant. Testing done. 
`def min_degree_of_vertex_in_max_ind_set(g):
    """
    Returns the minimum degree of any vertice that is a part of any maximum indepdendent set
    
    sage: min_degree_of_vertex_in_max_ind_set(c4)
    2
    sage: min_degree_of_vertex_in_max_ind_set(pete)
    3
    """
    
    low_degree = g.order()
    list_of_vertices = []
   
    UnionSet = Set({})
    IndSets=find_all_max_ind_sets(g)
    
    for s in IndSets:
        #print s,UnionSet
        UnionSet = UnionSet.union(Set(s))
    
    list_of_vertices = list(UnionSet)
    
    for num in list_of_vertices:
        if g.degree(num) < low_degree:
            low_degree = g.degree(num)
    
    print low_degree`
