### ISSUE TITLE
Add bavelas_index invariant to gt.sage

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#368]
Let s(x) be the sum of the distances from x to each other vertex.

Then bavelas_index = sum(s(x)/s(y)),
where the sum is taken over all edges xy in the graph.

See (attached):
Sabidussi, Gert. "The centrality index of a graph." Psychometrika 31.4 (1966): 581-603.
[sabidussi-centrality-index-1966.pdf](https://github.com/math1um/objects-invariants-properties/files/1111302/sabidussi-centrality-index-1966.pdf)

**Comment by cjoshea9** [comment]
Working code for the bavelas_index invariant. Tests have been run. 

`def bavelas_index(g):
    """
    sum over all edges (v,w) of (distance from v to all other vertices)/(distance from w to all other vertices)
    computes each edge twice (once with v computation in numerator, once with w computation in numerator)
    
        sage: bavelas_index(p6)
        5086/495
        sage: bavelas_index(k4)
        12
        
    """
    D = g.distance_all_pairs()

    def s_aux(v): #computes sum of distances from v to all other vertices
        sum = 0
        for w in g.vertices():
            sum += D[v][w]
        return sum

    sum_final = 0

    for edge in g.edges(labels=false):
        v = edge[0]
        w = edge[1]
        sum_final += (s_aux(w) / s_aux(v)) + (s_aux(v) / s_aux(w))

    print sum_final`
