### ISSUE TITLE
Add beuchamp_index to gt.sage

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#369]
See p.597:
Sabidussi, Gert. "The centrality index of a graph." Psychometrika 31.4 (1966): 581-603.

paper attached in issue #368.

**Comment by cjoshea9** [comment]
Code for the beauchamp_index

`def beauchamp_index(g):
    """
    Defined on page 597 of sabidussi-centrality-index-1966.pdf
    
    sage: beauchamp_index(c4)
    1
    sage: beauchamp_index(p5)
    137/210
    sage: beauchamp_index(pete)
    2/3
    """
    
    D = g.distance_all_pairs()

    def s_aux(v): #computes sum of distances from v to all other vertices
        sum = 0
        for w in g.vertices():
            sum += D[v][w]
        return sum

    sum_final = 0

    for v in g.vertices():
        sum_final += 1/s_aux(v)

    print sum_final`
