### ISSUE TITLE
Add graph Willis' thesis p.21

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#37]
Please add a note for what;'s special about this graph.

**Comment by shivejl** [comment]
I'll take this.

**Comment by shivejl** [comment]
Feel free to check:

'KoD?Xb?@hBBB'

This is a graph for which n/chi gives a better estimate for alpha than any of the other lower bounds (alpha=4, n=12, e=20, chi=3, Delta=4, dbar=3.34, lambda1=3.41)

**Comment by rbarden** [comment]
Added
