### ISSUE TITLE
Add 6 sabidussi graphs to gt.sage

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#370]
See:
Sabidussi, Gert. "The centrality index of a graph." Psychometrika 31.4 (1966): 581-603.

call these sabidussi_1, etc.

paper attached in issue #368.

**Comment by cjoshea9** [comment]
The first graph in the paper is isomorphic to the Frucht graph which we already have
sabidussi_2 = Graph('Ls_aGcKSpiDCQH')
sabidussi_3 = Graph('H`?NeW{')
sabidussi_4 = Graph('L?O_?C@?G_oOF?')
sabidussi_5 = Graph('L??GH?GOC@AWKC')
sabidussi_6 = Graph('L??G?COGQCOCN?')

Graphs 2,3,4,5,6 are new graphs that we do not have yet
