### ISSUE TITLE
check zero_eigenvalues for each graph in db

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#371]
this count will be off due to very tiny numerical errors. but can easily be hand-checked. correct counts should be hard-coded in gt_database.sage and then updated

NOTE: any changes necessarily effect numbers of positive_eigenvalues, etc, and these will have to be appropriately modified.

it may be useful to have a utility that checks that numbers of zero, positive, and negative eigenvalues sum to the order (n) for each graph

**Comment by yirkajk** [comment]
Brought back up in Issue #578.
I'm closing this issue in favor of the new conversation.
