### ISSUE TITLE
add Jorgensen paper graphs to gt.sage

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#372]
3 graphs on p.348.

see (attached):
Jørgensen, Leif K. "Diameters of cubic graphs." Discrete applied mathematics 37 (1992): 347-351.
[jorgenson-diameters-of-cubic-graphs-1992.pdf](https://github.com/math1um/objects-invariants-properties/files/1116113/jorgenson-diameters-of-cubic-graphs-1992.pdf)

**Comment by cjoshea9** [comment]
jorgenson1 = Graph('Ss??GOG?OC?_?I?DGCa?oDO?i??_C@?AC')
jorgenson2 = Graph('GtP@Ww')

Tested for isomorphism with graph_objects
The third graph on the page is isomorphic to the Wagner graph
