### ISSUE TITLE
Add Pepper graph to graphs.sage

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#376]
Pepper found a counterexample to the conjecture:
alpha >= diameter for regular graphs.

he has continued to explore the relationship between alpha and diameter in regular graphs, and believes diameter can be made arbitrarily larger than alpha.

"[the attached graph] has alpha of 10 and diameter of 13 and is cubic graph. Now I also think I understand idea how to make larger difference than any constant...can always make cubic graphs or nearly cubic with independence ratio less than one half, less by larger and larger constant as n grows, but for which there are still no shortcuts and diameter close to half order. On the other hand, with these, as n grows, ratio of alpha and diameter still may approach 1 even as their difference grows arbitrarly large."

See the attached graph:
![20170702_090618](https://user-images.githubusercontent.com/2118748/27782332-1206db28-5fa0-11e7-8959-7065897e4ef1.jpg)

**Comment by cjoshea9** [comment]
pepper = Graph('Yv?GW?@?WB?A?A?@_?oGA?_KG????G??K??A???W??@???AO??BG??B?')

Pepper graph has been tested for isomorphism versus all_graphs
