### ISSUE TITLE
Add CE2 to alpha-diameter conjecture to graphs.sage

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#378]
Conjecture: For a regular graph,
alpha >= diameter - 1

From R. Pepper (3 July 2017):

"Just found better by far solution, attached. Shows neither difference nor ratio can be close for some graphs and diameter way larger in every way, twice as high in fact. Seems like because of this, the best you could have is alpha at least half of diameter, but then you are worse off than radius lower bound, which is also at least half diameter,  and so follows from transitivity."
![20170703_111326](https://user-images.githubusercontent.com/2118748/27801862-5a96d89a-5fee-11e7-81d5-d5918f1fbdd5.jpg)

**Comment by cjoshea9** [comment]
`pepper_1_gadget = Graph('Ot???CA?WB`_B@O_B_B?A')`

**Comment by cjoshea9** [comment]
pepper_1_gadget = Graph('Ot???CA?WB`_B@O_B_B?A')
