### ISSUE TITLE
Add p6707 to graphs.sage

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#379]
NB: For example, independence_number(x)<=welsh_powell(x)^e^different_degrees(x) is false for the path on 6707 

It should be possible to calculate any invariant of p6707 by hand. Can Sage calculate them? Of course, we'd like to precompute them!

Adding p6707 using the (huge!) g6 string is definitely the wrong way to go here. Just use the built-in PathGraph constructor.

**Comment by rbarden** [comment]
Added the graph, not added to any list yet.

**Comment by rbarden** [comment]
It takes forever to calculate most invariants for p6707. We'll definitely need to precompute them and use the database, or find a smaller CE.
