### ISSUE TITLE
Open Conjecture: alpha >= max(max_even_minus_even_horizontal, 1/2*lovasz_theta)

### ISSUE THREAD

**Issue by cjoshea9** [math1um/objects-invariants-properties#383]
This conjecture is true for all connected graphs with up to 8 vertices

**Comment by cjoshea9** [comment]
This conjecture works for random graphs with 20 to 60 vertices. (I tested 1000 graphs with 20 vertices, 21 vertices, 22 vertices, etc.)

**Comment by a234** [comment]
The Paley graph of order 101 is a counterexample.
