### ISSUE TITLE
Add graph from Willis' thesis p.3.3

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#39]
please add the description from the caption

**Comment by shivejl** [comment]
I'll take this.

**Comment by shivejl** [comment]
Feel free to check:

'Mts?GKE@QDCIQIKD?'

The graph for which Radius gives a better estimate for alpha than any of the other lower bounds considered (alpha=4, n=14, e=28, chi=4, Delta=4, dbar=4, lambda1=4)

**Comment by rbarden** [comment]
Added.
