### ISSUE TITLE
Add examples of Caro-Roditty graphs

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#395]
G_1 is a 4-cycle
G_2 is a 4-cycle with each vertex adjacent to the corresponding vertex in G_1.
G_n is a 4-cycle with each vertex adjacent to the corresponding vertex in last layer of G_(n-1).

A generator would be great. Examples of G_3 and G_4 would be good enough.

These graph are mentioned in p.171 of (attached):
Caro, Y., and Y. Roditty. "On the vertex-independence number and star decomposition of graphs." Ars Combinatoria 20 (1985): 167-180.
[caro-roditty-independence-star-decomposition-1985.pdf](https://github.com/math1um/objects-invariants-properties/files/1183998/caro-roditty-independence-star-decomposition-1985.pdf)

**Comment by rbarden** [comment]
Paper is not attached.
