### ISSUE TITLE
Add LEL invariant

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#403]
LEL stands for laplacian-energy-like in (attached):
Liu, Jianping, and Bolian Liu. "A Laplacian-energy-like invariant of a graph." MATCH-COMMUNICATIONS IN MATHEMATICAL AND IN COMPUTER CHEMISTRY 59.2 (2008): 355-372.

LEL is defined to equal the sum of the square-roots of the laplacian eigenvalues of a graph.

[liu-liu-laplacian-energy-like-invariant-2008.pdf](https://github.com/math1um/objects-invariants-properties/files/1201279/liu-liu-laplacian-energy-like-invariant-2008.pdf)

**Comment by rbarden** [comment]
```
def laplacian_energy_like(g):
    """
    Returns the sum of the square roots of the laplacian eigenvalues

    Liu, Jianping, and Bolian Liu. "A Laplacian-energy-like invariant of a graph." MATCH-COMMUNICATIONS IN MATHEMATICAL AND IN COMPUTER CHEMISTRY 59.2 (2008): 355-372.
    """
    return sum([sqrt(x) for x in g.spectrum(laplacian = True)])
```
