### ISSUE TITLE
Add Goedgebeur graph

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#405]
This is the smallest 4-critical graph with girth 5 and maximum degree 7.

See graph on p.5 of:
https://arxiv.org/pdf/1707.07581.pdf

**Comment by Neogeo44** [comment]
Graph is on pg 10.

Code for graph:
'U???CA?O?O_aGC?`A@?HDGQOPAA@AGE@?Gc@~_??'

Made with house of graphs
