### ISSUE TITLE
Add graph: Erdos-Saks-Sos

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#413]
see p. 10 of (attached):
Erdös, Paul, Michael Saks, and Vera T. Sós. "Maximum induced trees in graphs." Journal of Combinatorial Theory, Series B 41.1 (1986): 61-79.
[erdos-saks-sos-maximum-induced-trees-1986.pdf](https://github.com/math1um/objects-invariants-properties/files/1244731/erdos-saks-sos-maximum-induced-trees-1986.pdf)

**Comment by Neogeo44** [comment]
Graph:
'~?@R`?G?CK?w??@?@??_?G?@??C??G??G??C??@???G???_??@???@AA??????OG????_???@?????O?A??K????@_????E?????...'

Made with house of graphs

**Comment by yirkajk** [comment]
I can't copy & paste the graph6 string you gave. The characters were corrupted.
I redrew it and got ``` 'lhCH_C@?G?_K?@??_W??@??K??G??G??K??@???G??C???@??B?????_???G???@????o????G????G??_??????@?????G?????_????K?????@??????_?A??G??????@??????C??????G?????@_??????C??????@' ```

**Comment by yirkajk** [comment]
This graph already exists as `C20Pow04`
