### ISSUE TITLE
Add Thomassen graphs

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#414]
See:
http://mathworld.wolfram.com/ThomassenGraphs.html

**Comment by Neogeo44** [comment]
Thomassen graph 41
'~?@R`?G?CK?w??@?@??_?G?@??C??G??G??C??@???G???_??@???@AA??????OG????_???@?????O?A??K????@_????E?????...'

Thomassen graph 34
'~?@R`?G?CK?w??@?@??_?G?@??C??G??G??C??@???G???_??@???@AA??????OG????_???@?????O?A??K????@_????E?????...'

Thomassen graph 32
'~?@R`?G?CK?w??@?@??_?G?@??C??G??G??C??@???G???_??@???@AA??????OG????_???@?????O?A??K????@_????E?????...'

Thomassen graph 20
'~?@R`?G?CK?w??@?@??_?G?@??C??G??G??C??@???G???_??@???@AA??????OG????_???@?????O?A??K????@_????E?????...'
3

The Thomassen 60, 94 and 105 are too small to clearly read.

Made with house of graphs.

**Comment by yirkajk** [comment]
I was unable to use any of the strings you posted above; they were corrupted in some way.
I generated new strings using Mathematica, which has them all built in 😄.

**Comment by nvcleemp** [comment]
The reason the strings are corrupted is because they aren't properly escaped and thus are parsed as Markdown. You can click on edit and copy the original text. That should work.

**Comment by nvcleemp** [comment]
OK, I edited the comment above and escaped the strings, but you are right: they are corrupt. They were shortened and an ellipsis was added at the end, so this is just a display string from HoG and not the full g6 string.
