### ISSUE TITLE
Add graphs: 2 graphs from Chratrand text

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#417]
see (attached) Figures 5.4 and 5.5 from p.203 of:
Chartrand, Gary, Linda Lesniak, and Ping Zhang. Graphs & digraphs. Vol. 39. CRC press, 2010.

[chartrand-p203.pdf](https://github.com/math1um/objects-invariants-properties/files/1250773/chartrand-p203.pdf)

**Comment by Neogeo44** [comment]
Figure 5.4  'I?_aCwvUw'
Figure 5.5  'K??H?C@?W`z_'
