### ISSUE TITLE
Add graph from Lazebnik

### ISSUE THREAD

**Issue by Neogeo44** [math1um/objects-invariants-properties#424]
Graph on Page 7 of
http://www.math.udel.edu/~lazebnik/papers/v17i1r170.pdf

Graph is below

'e?????????????????????G??O??O??G???_??C??A???O?K???o????W???W??????????????????????[???`A???C__???PO...'

**Comment by yirkajk** [comment]
I was unable to load your graph6_string. Sage reported invalid or corrupt characters.
I redrew the graph. This is the string I will be adding: 
```P????????????@?@?Y?@UBEO```

**Comment by math1um** [comment]
This graph should be moved to a "disconnected graphs" list - that's not included with the main graph_objects list.

Many invariants are not defined for disconnected graphs, They can be - some definitions can be extended in natural ways - but not distance invariants - and these will break conjectures - especially when we mean to interpret conjectures as for "connected graphs".
