### ISSUE TITLE
Add Graphs from page 37 of David Joyner's Algorithmic Graph Theory In Sage

### ISSUE THREAD

**Issue by Neogeo44** [math1um/objects-invariants-properties#432]
Add the following graphs:
(G6 strings)

```
'E@~w'
'F@N]w'
'GIaHx{'
'HIaJ`{~'

```

**Comment by a234** [comment]
What's the point?

**Comment by Neogeo44** [comment]
interesting graphs from pp 37 of 
http://www.freetechbooks.com/algorithmic-graph-theory-and-sage-t974.html

**Comment by yirkajk** [comment]
Commit 1c16b6006f9a1e27bbfc093ec96ecad18407c31a
