### ISSUE TITLE
Add all known distance-regular graphs to gt.sage

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#436]
Here's a list of all strongly regular graphs up to 64 vertices:
http://www.maths.gla.ac.uk/~es/srgraphs.php

Wikipedia has a list of all cubic distance regular graphs:
https://en.wikipedia.org/wiki/Distance-regular_graph

NOTE: the Wikipedia mentions a few more examples of distance-redgular graphs. Which ones are in gt.sage? Which ones need to be added?

How can we add a graph? You need a representation of the graph. A good one is graph6 strings. 

MY NEW DISTANCE_REGULAR graphs is:
`DqK
`
(actually this is C5 - not new)

**Comment by math1um** [comment]
You can check if your "new" graph is in gt.sage. here's an example:

`my_graph = Graph("DqK")

for g in graph_objects:
    if g.is_isomorphic(my_graph):
        print "my_graph is already there. woo-hoo!"
        break`

**Comment by math1um** [comment]
You can enter a graph using a visual editor at House of Graphs:
https://hog.grinvin.org/

And can also get the g6 string of your graph there. (make an account and use "search for graph"

**Comment by lambda-funcptr** [comment]
Here's a quick little script for pulling in the distance regular graphs from [http://www.maths.gla.ac.uk/~es/srgraphs.php](http://www.maths.gla.ac.uk/~es/srgraphs.php).

`import urllib2

def tupleize_and_numericize(s):
    return map(lambda c: int(c), tuple(s))

def parse_graph(string):
    graphMatrix = Matrix(map(lambda s: tupleize_and_numericize(s), string.split('\n')))
    return Graph(graphMatrix)

def check_if_unique(graph):
    for oldGraph in graph_objects:
        if graph.is_isomorphic(oldGraph):
            return false

    return true

url_info = 'http://www.maths.gla.ac.uk/~es/SRGs/64-18-2-6'
response = urllib2.urlopen(url_info)
txtresponse = response.read()

rawStrings = txtresponse.split("\n\n")

filter(check_if_unique, map(parse_graph, rawStrings[1:len(rawStrings)-2]))`

**Comment by lambda-funcptr** [comment]
Here's a list of the graph6 strings, LF new line separated.

[g6strings.txt](https://github.com/math1um/objects-invariants-properties/files/2031646/g6strings.txt)

To reproduce and sort by graph families, there's this:

```python
import urllib2
import bz2

def tupleize_and_numericize(s):
    return map(lambda c: int(c), tuple(s))

def parse_graph(string):
    graphMatrix = Matrix(map(lambda s: tupleize_and_numericize(s), string.split('\n')))
    return Graph(graphMatrix)

def check_if_unique(graph):
    for oldGraph in graph_objects:
        if graph.is_isomorphic(oldGraph):
            return false

    return true

def pull_data(url_info):
    response = urllib2.urlopen(url_info)
    txtresponse = response.read()
    rawStrings = txtresponse.split("\n\n")

    return filter(check_if_unique, map(parse_graph, rawStrings[1:len(rawStrings)-2]))

def pull_data_bzip(url_info):
    response = urllib2.urlopen(url_info)
    bzip2response = response.read()
    unzipped = bz2.decompress(bzip2response)
    rawStrings = unzipped.split("\n\n")

    return filter(check_if_unique, map(parse_graph, rawStrings[1:len(rawStrings)-2]))

sr_graphs = dict()

sr_graphs["52-0-1"] = pull_data("http://www.maths.gla.ac.uk/~es/SRGs/5-2-0-1")
sr_graphs["9-4-1-2"] = pull_data("http://www.maths.gla.ac.uk/~es/SRGs/9-4-1-2")
sr_graphs["10-3-0-1"] = pull_data("http://www.maths.gla.ac.uk/~es/SRGs/10-3-0-1")
sr_graphs["13-6-2-3"] = pull_data("http://www.maths.gla.ac.uk/~es/SRGs/13-6-2-3")
sr_graphs["13-6-2-3"] = pull_data("http://www.maths.gla.ac.uk/~es/SRGs/15-6-1-3")
sr_graphs["16-5-0-2"] = pull_data("http://www.maths.gla.ac.uk/~es/SRGs/16-5-0-2")
sr_graphs["16-6-2-2"] = pull_data("http://www.maths.gla.ac.uk/~es/SRGs/16-6-2-2")
sr_graphs["17-8-3-4"] = pull_data("http://www.maths.gla.ac.uk/~es/SRGs/17-8-3-4")
sr_graphs["21-10-3-6"] = pull_data("http://www.maths.gla.ac.uk/~es/SRGs/21-10-3-6")
sr_graphs["25-8-3-2"] = pull_data("http://www.maths.gla.ac.uk/~es/SRGs/25-8-3-2")
sr_graphs["25-12-5-6"] = pull_data("http://www.maths.gla.ac.uk/~es/SRGs/25-12-5-6")
sdr_graphs["26-10-3-4"] = pull_data("http://www.maths.gla.ac.uk/~es/SRGs/26-10-3-4")
sr_graphs["27-10-1-5"] = pull_data("http://www.maths.gla.ac.uk/~es/SRGs/27-10-1-5")
sr_graphs["28-12-6-4"] = pull_data("http://www.maths.gla.ac.uk/~es/SRGs/28-12-6-4")
sr_graphs["29-14-6-7"] = pull_data("http://www.maths.gla.ac.uk/~es/SRGs/29-14-6-7")
sr_graphs["35-18-9-9"] = pull_data("http://www.maths.gla.ac.uk/~es/SRGs/35-18-9-9")
sr_graphs["36-10-4-2"] = pull_data("http://www.maths.gla.ac.uk/~es/SRGs/36-10-4-2")
sr_graphs["36-14-4-6"] = pull_data("http://www.maths.gla.ac.uk/~es/SRGs/36-14-4-6")
sr_graphs["36-14-7-4"] = pull_data("http://www.maths.gla.ac.uk/~es/SRGs/36-14-7-4")
sr_graphs["37-18-8-9"] = pull_data_bzip("http://www.maths.gla.ac.uk/~es/SRGs/37-18-8-9.bz2")
sr_graphs["40-12-2-4"] = pull_data("http://www.maths.gla.ac.uk/~es/SRGs/40-12-2-4")
sr_graphs["45-12-3-3"] = pull_data("http://www.maths.gla.ac.uk/~es/SRGs/45-12-3-3")
sr_graphs["49-12-5-2"] = pull_data("http://www.maths.gla.ac.uk/~es/SRGs/49-12-5-2")
sr_graphs["50-21-8-9"] = pull_data("http://www.maths.gla.ac.uk/~es/SRGs/50-21-8-9")
sr_graphs["64-18-2-6"] = pull_data("http://www.maths.gla.ac.uk/~es/SRGs/64-18-2-6")
```

**Comment by math1um** [comment]
All cubic distance-regular graphs are in gt.sage (as reported by Wiukipedia):

The cubic distance-regular graphs have been completely classified.

The 13 distinct cubic distance-regular graphs are K4 (or tetrahedron), K3,3, the Petersen graph, the cube, the Heawood graph, the Pappus graph, the Coxeter graph, the Tutte–Coxeter graph, the dodecahedron, the Desargues graph, Tutte 12-cage, the Biggs–Smith graph, and the Foster graph.

**Comment by math1um** [comment]
Of most interest are examples of distance-regular graphs that aren't strongly regular.

**Comment by thenealon** [comment]
The following graphs are all the ones I've found so far that are:

- order at most 15
- distance regular
- not strongly regular
- not already in gt.sage

(each line is a graph6 string, and the two sets are bipartite/non-bipartite resp.)

**Bipartite DRGs:**
```
QKUalPTiaitSTTiiIilTSTTUii_
IKUalPTi_
KKUalPTiaitS
SKUalPTiaitSTTiiIilTSTTUiiaiilTTO
MKUalPTiaitSTTii?
OKUalPTiaitSTTiiIilTS
```

**Non-bipartite DRGs:**
```
L~~~~~~~~~~~~~
N~~~~~~~~~~~~~~~~~w
P~~~~~~~~~~~~~~~~~~~~~~{
J~~~~~~~~~_
Q~~~~~~~~~~~~~~~~~~~~~~~~~w
M~~~~~~~~~~~~~~~_
R~~~~~~~~~~~~~~~~~~~~~~~~~~~~w
O~~~~~~~~~~~~~~~~~~~~
K~~~~~~~~~~~
S~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~{
```

**Comment by yirkajk** [comment]
I'm going to add everything that's been posted so far, and then I'll close this issue.

**Comment by yirkajk** [comment]
> Add k3_3 to gt.sage:
k3_3 = graphs.CompleteBipartiteGraph(3, 3)

This graph already exists as "Thomsen Graph".
