### ISSUE TITLE
is_fan name problem?!

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#438]
gt.sage property is named after: genghua fan

confusing because there is a class of graphs called "fan graphs". see:
http://mathworld.wolfram.com/FanGraph.html

in the first sense, these graphs are ALL hamiltonian

in the 2nd sense, there are non-hamiltonian fan graphs

**Comment by yirkajk** [comment]
Fixed. Commit: https://github.com/math1um/objects-invariants-properties/commit/19add8724d557045816bb0d86a673a1de7d80481
