### ISSUE TITLE
Update and improve documentation in readme and webpage

### ISSUE THREAD

**Issue by yirkajk** [math1um/objects-invariants-properties#442]
Current example runs on the full database.
Also, the current example uses an incorrect name for efficient_invariants

**Comment by nvcleemp** [comment]
Besides the README, there is also the website: https://math1um.github.io/objects-invariants-properties/

**Comment by yirkajk** [comment]
I just pushed an updated readme and I copied that document into the project webpage.
There's always more documentation to be done (ex. contributing guidelines), but that should be enough to close this issue.
