### ISSUE TITLE
Add Ham1 to GT

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#444]
ham1 = Graph("I~EGYCxyG")

this graph is hamiltonian but doesn't satify any of these known sufficient conditions:

theorem_s1 = lambda g: g.is_bipartite() and g.is_strongly_regular()
theorem_s2 = lambda g: g.is_circular_planar() and g.is_bipartite()

theorems = [Graph.is_cycle, Graph.is_clique, theorem_s1, is_ore, is_dirac, is_chvatal_erdos, theorem_s2]

**Comment by yirkajk** [comment]
Added.
Commit: https://github.com/math1um/objects-invariants-properties/commit/955430655bb692fd969724edec6e6f24bbf3c819
