### ISSUE TITLE
Add necklace generator & necklace(3) to GT

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#447]
A "necklace" is formed by adding some number of kites, glued tip to tail.

if you take a necklace formed by three of these, its hamiltonian, regular and HAS a kite, and this a CE to the conjecture:

(is_hamiltonian)->(((is_regular)->(is_kite_free)&any other property

**Comment by thenealon** [comment]
I'm calling this function "kite_necklace", because a necklace seems to be something else (see, e.g., Handbook of Graph Theory p750 problem D14).  

```
def kite_necklace(k):
    #returns k kites joined head to tail
    if k==1:
        return Graph('DJk')
    g = graphs.CycleGraph(2*k)
    for i in [0..k-1]:
        g.subdivide_edge((0+2*i,1+2*i),1)
        g.add_edge(0+2*i,1+2*i)
        g.subdivide_edge((0+2*i,1+2*i),1)
        g.add_edge(2*k+2*i,2*k+2*i+1)
    return g
```

**Comment by yirkajk** [comment]
Added. Commit: https://github.com/math1um/objects-invariants-properties/commit/f5916b6270766384c61745f4a6248c9da45d3da8
