### ISSUE TITLE
Known Theorems

### ISSUE THREAD

**Issue by thenealon** [math1um/objects-invariants-properties#450]
Known Theorems, all produced by conjecturing:

```
(is_chvatal_erdos)->(is_hamiltonian)
((is_lindquester)|(is_ore))->(is_hamiltonian)
(is_generalized_dirac)->(is_hamiltonian)
(is_haggkvist_nicoghossian)->(is_hamiltonian)
(is_fan)->(is_hamiltonian)
((is_cycle)|(is_clique))->(is_hamiltonian)
```

**Comment by yirkajk** [comment]
Here is the code to add to theorems.sage, once we have citations.
```
add_to_lists(is_chvatal_erdos, hamiltonian_sufficient, all_theorems)
add_to_lists(is_generalized_dirac, hamiltonian_sufficient, all_theorems)
add_to_lists(is_haggkvist_nicoghossian, hamiltonian_sufficient, all_theorems)

### This is the correct fan definition, yes? ###
add_to_lists(is_genghua_fan, hamiltonian_sufficient, all_theorems)

def is_lindquester_or_is_ore(g):
    return is_lindquester(g) or is_ore(g)
add_to_lists(is_lindquester_or_is_ore, hamiltonian_sufficient, all_theorems)

def is_cycle_or_is_clique(g):
    return is_cycle(g) or g.is_clique()
add_to_lists(is_cycle_or_is_clique, hamiltonian_sufficient, all_theorems)
```

**Comment by a234** [comment]
is_lindquester: Lindquester, T. E. (1989). The effects of distance and neighborhood union conditions on hamiltonian properties in graphs. Journal of Graph Theory, 13(3), 335-352.
is_generalized_dirac: The Lindquester condition is weaker than the generalized Dirac condition, since it only involves distance-2 pairs.

**Comment by thenealon** [comment]
The reference for is_generalized_dirac is:

R.J Faudree, Ronald J Gould, Michael S Jacobson, R.H Schelp, Neighborhood unions and hamiltonian properties in graphs, Journal of Combinatorial Theory, Series B, Volume 47, Issue 1, 1989, Pages 1-9

**Comment by yirkajk** [comment]
Thank you @a234!
