### ISSUE TITLE
CE to ((is_van_den_heuvel)&(is_circular_planar))->(is_hamiltonian)

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#453]
umbrella_4 = Graph("Ep{G")

Add to gt.sage

**Comment by math1um** [comment]
Add to GT

**Comment by yirkajk** [comment]
Added. Commit: https://github.com/math1um/objects-invariants-properties/commit/473f600d98f095fe87d144e0f7cc3583442cf5a2
