### ISSUE TITLE
PROPERTY: need code for 4-connectness

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#458]
the current obvious algorithm is to check connectivity using Sage's built-in connectivity method.

something specific for 4-connectivity *should* be faster - and would be helpful in an investigation of graph hamiltonicity.

**Comment by a234** [comment]
Perhaps using the k-parameter of vertex connectivity, e.g. 
```g.vertex_connectivity(k=3)```?

**Comment by yirkajk** [comment]
Unfortunately, CoCalc has only updated to Sage 8.1. Still waiting for Sage 8.2. We're using CoCalc, so it's difficult to test.
I've contacted CoCalc, asking how long until the update.

**Comment by thenealon** [comment]
Here's the brutalist approach (when in doubt, make for loops). There may be better algorithms  [here](https://www.cse.msu.edu/~cse835/Papers/Graph_connectivity_revised.pdf).

```
def is_four_connected(g):
    if g.order()<5:
        return false
    for S in Subsets(g.vertices(),3):
        h=copy(g)
        h.delete_vertices(S)
        if not h.is_connected():
            return false
    return true
```

**Comment by math1um** [comment]
NOTE: its always good to code the "naive" algorithm. Then you can check it against any improved algorithms.

**Comment by yirkajk** [comment]
Okay, we got access to Sage 8.2 and I was able to use the `k` parameter for `g.vertex_connectivity()`
Thank you for the suggestion @a234!
