### ISSUE TITLE
Error in is_subcubic?

### ISSUE THREAD

**Issue by thenealon** [math1um/objects-invariants-properties#459]
Is a cycle subcubic?  It seems like it should be; however, the is_subcubic function only returns true if max_degree == 3 -- not if max_degree<=3.

```
# Graph is subcubic is each vertex is at most degree 3
def is_subcubic(g):
    return max_degree(g) == 3
```

**Comment by yirkajk** [comment]
Commit ce4828ef0dd6bf7e84b2655eb28e8b6143d433d5
