### ISSUE TITLE
Conjecture: Every locally unicyclic graph is hamiltonian 

### ISSUE THREAD

**Issue by a234** [math1um/objects-invariants-properties#462]
A graph is unicyclic if it is connected and has order==size.
A graph is locally unicyclic if all of its local subgraphs are unicyclic.
```
def is_locally_unicyclic(g):
    V = g.vertices()
    for v in V:
        N = g.neighbors(v)
        if len(N) > 0:
            GN = g.subgraph(N)
            if not (GN.is_connected() and GN.order()==GN.size()):
                return False
    return True

**Comment by yirkajk** [comment]
Where does your definition of unicylic come from?

In this link: http://mathworld.wolfram.com/UnicyclicGraph.html
Unicylic graphs are defined as connected with exactly one cycle.
The [bull graph](https://hog.grinvin.org/ViewGraphInfo.action?id=240) is unicyclic under this definition, but not yours.

**Comment by nvcleemp** [comment]
Bothe definitions are equivalent, and the bull graph is unicyclic under both definitions. Note however that the code given is for _locally_ unicyclic. The bull graph is indeed not locally unicyclic.

**Comment by thenealon** [comment]
Unsurprisingly, I agree with Nico -- this is a correct definition of locally unicyclic.  I've viciously stolen part of it to make a (non-local) unicyclic property:

```
def is_unicyclic(g):
    return (g.is_connected() and g.order()==g.size())
```

**Comment by yirkajk** [comment]
Added property (by the way, the `localise(f)` function, already defined in Properties, is useful).

Is this conjecture still open? No known counterexamples?

**Comment by thenealon** [comment]
It is still open; I suspect it is actually true.

**Comment by a234** [comment]
I'm puzzled with the ```localise(f)``` function.
For example, let ```G=graphs.IcosahedralGraph()```. G is not locally bipartite.
But ```localise(G.is_bipartite)(G)``` returns ```True```, while the ```is_locally_bipartite(G)``` function returns the correct value, ```False```.

**Comment by thenealon** [comment]
This is a syntax issue -- the method should be the general method name, not called on a specific graph G.
`localise(Graph.is_bipartite)(G)` returns `False`, as it should.

**Comment by nvcleemp** [comment]
...and the `localise` function was mainly written to be used as this:

```
is_locally_bipartite = localise(Graph.is_bipartite)
```

This was meant to reduce the number of duplicated lines of code due to every property having a local version.

**Comment by sarah1347** [comment]
Counter-example: Two K_4 joined by an edge. 
It is locally unicyclid: the neighborhoods of the vertices of degree 3 are triangles and the neighborhoods of the vertices of degree 4 are a triangle and an isolated vertex. 
It is not hamiltonian: the vertices of degree 4 are cut-vertices.

**Comment by sarah1347** [comment]
The conjecture is false. Take two K_4 joined by an edge. Then the neighborhoods of the vertices of degree 4 are disconnected, but have one cycle. Add two cross edges to make the neighborhoods connected (these involve the endpoints of the added edge). The new graph is locally connected, but Hamiltonian. 
However, we can clone one copy of the K_4 + additional edges (giving three K_4 and 6 edges total). This is still locally connected, but is no longer Hamiltonian since the non-cloned copy of K_4 has a cut set of size 2 that gives 3 components.

**Comment by math1um** [comment]
Here's Sarah's graph:
`sarah = graphs.CompleteGraph(4)
sarah = sarah.disjoint_union(graphs.CompleteGraph(4))
sarah = sarah.disjoint_union(graphs.CompleteGraph(4))
sarah.relabel()
sarah.add_edges([(8,3),(8,7),(9,0),(9,3),(9,4),(9,7)])`

Checked: it is locally unicyclic and NOT hamiltonian.

g6 string is 'K~?GW[PeW@_F'

Should be added to GT.
