### ISSUE TITLE
Counterexamples to a couple of necessary conjectures

### ISSUE THREAD

**Issue by JRParrish** [math1um/objects-invariants-properties#464]
#Necessary condition conjecture counterexamples:

#CE to (is_hamiltonian)->((order_leq_twice_max_degree)|(is_locally_bipartite))
(Hamiltonian graph that does not have order less than or equal to twice its max degree and is not locally bipartite)
CE_graph_3 = Graph('LdEIDOHA{dc_Sa')

#CE to (is_hamiltonian)->(((is_regular)->(is_kite_free))&(matching_covered))
#ALSO CE to (is_hamiltonian)->(((is_regular)->(is_kite_free))&(alpha_leq_order_over_two))
(regular graph that contains a kite and a Hamiltonian cycle)
CE_graph_5 = Graph('Gv?IXW')

**Comment by yirkajk** [comment]
Added first graph to database as ce144.
CE_graph_5 is regular_non_trans, already in the database
