### ISSUE TITLE
Property: Rahman-Kaykobad sufficient condition for Hamiltonicity

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#465]
If graph G is 2-connected and, for every non-adjacent pair v and w, the sum of the degrees and their distance is at least order n + 1, with d(v)+d(w)+dist(v,w)>n+1 for at least one pair (strict inequality) then the graph is hamiltonian.

Add to gt.sage

efficiently computable!

Rahman, M. Sohel, and Mohammad Kaykobad. "On Hamiltonian cycles and Hamiltonian paths." Information Processing Letters 94.1 (2005): 37-41. (attached)

[kaykobad-hamiltonicity-2005.pdf](https://github.com/math1um/objects-invariants-properties/files/2058440/kaykobad-hamiltonicity-2005.pdf)

**Comment by thenealon** [comment]
```
def rahman_kaykobad(g):
    if not is_two_connected(g):
        return false
    n=g.order()
    if g.size() == g.order()*(g.order()-1)/2:
        return true
    Dist = g.distance_all_pairs()
    return (min(g.degree(v) + g.degree(w) + Dist[v][w] for v in g for w in g if Dist[v][w] > 1)>n) and (max(g.degree(v) + g.degree(w) + Dist[v][w] for v in g for w in g if Dist[v][w] > 1)>n+1)
```

**Comment by math1um** [comment]
NOTE: this property is not defined for complete graphs, thus it needs a defined value for this special case. since its a sufficient condition for hamiltonicity, the definition should be true. but this special case should be mentioned in a doctest.

Add doctests: rahman_kaykobad(graphs.CycleGraph(7))==True

rahman_kaykobad(graphs.PetersenGraph())==False

**Comment by yirkajk** [comment]
Just to check, are you referring to their Theorem 1.6?
> Let G = (V ,E) be a connected graph with n vertices such that for all pairs of distinct nonadjacent vertices u,v ∈ V,  we have d(u) + d(v) + dist(u, v) >= n + 1. Then, G has a Hamiltonian path.

This isn't what you stated, but it's the closest to what you stated that appears in this paper.

Also, I wouldn't say the property is "undefined" for complete graphs. It's just vacuously True.

**Comment by math1um** [comment]
The result is referenced on the Wikipedia "Hamilton Graph" page, which references this unpublished article:
https://drive.google.com/file/d/0BzaI8o9w-9jrQmFSZl9UMUFJM00/view

So, that's not a solid reference. 

This theorem is a slight improvement on Rahman and Kaykobad's published theorem (generalizing Ore's condition): if d(v)+d(w)+dist(v,w)>=1 for avert pair of non-adjacent vertices then the graph has a Hamiltonian path. So Kaykobad adds a slight strengthinging of this theorem's condition, and a strengthening of the conclusion from traceable to having a Hamilton cycle.

**Comment by yirkajk** [comment]
Okay, so, need to verify that theorem, then decide what to do with it.

**Comment by yirkajk** [comment]
@math1um and I are not confident in the statement or proof given by the latter paper "Hamiltonicity Revisited".
So, not adding this property or supposed theorem.
