### ISSUE TITLE
Utility: generalized degree of a set of vertices

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#467]
Let S be a set of vertices in a graph
Let N(S) = union of the neighborhoods N(v) of vertices v in S

Define generalized_degree(S) = |N(S)|

This number (which is *not* a graph invariant) shows up in Gould's hamiltonicity surveys.

See p.125 of: 
https://github.com/math1um/objects-invariants-properties/files/2058537/gould-hamilton-survey-1991.pdf

**Comment by thenealon** [comment]
```
def generalized_degree(g,S):
    return sum([g.degree(x) for x in S])
```

**Comment by a234** [comment]
This is incorrect, since the sum of vertex degrees could be larger than the size of the union of vertex neighborhoods.
Counterexample: Let g=S=C4. The correct value is 4, but your function returns 8.

**Comment by thenealon** [comment]
Thanks!  I think this is a fixed version (although maybe written in a silly way..)

```
def generalized_degree(g,S):
    nbrs=[]
    for x in S:
        nbrs=nbrs+g.neighbors(x)
    return len(list(Set(nbrs)))
```

**Comment by math1um** [comment]
looks good. should be added to GT.

doctest: generalized_degree(graphs.CompleteGraph(5),graphs.CompleteGraph(5).order())==5
