### ISSUE TITLE
Invariant: toughness

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#468]
Let the *toughness* of a graph G be the maximum of omega(G-S)/|S|, for every cut-set S, where omega(G') is the number of components of G'

1. Inefficient (the obvious algorithm is to search over all subsets S).

2. How to define for complete graphs (which have no cut-sets)?

This invariant shows up in investigations of Hamiltonicity (Chvatal, for instance).

**Comment by thenealon** [comment]
```
def toughness(g):
    y=subsets(g.vertices())
    o=g.order()
    minny=Infinity
    for x in subsets(g.vertices()):
        if not len(x)==0 and not len(x)==o:
            H=copy(g)
            H.delete_vertices(x)
            t=1.0*len(x)/H.connected_components_number()
            minny=min(t,minny)
    return minny
```

**Comment by thenealon** [comment]
This one should be double checked by somebody who knows what they're doing (not me).

**Comment by math1um** [comment]
Neal's definition differs from what I proposed but IS the definition in the literature. See:
https://en.wikipedia.org/wiki/Graph_toughness

**Comment by math1um** [comment]
Add doctest: toughness(p3)==0.5

Add to GT invariants
