### ISSUE TITLE
Properties: is_k_tough for real number k>=1

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#469]
toughness is defined in  Issue #468

A graph is k-tough if toughness <= k

k=1 and k=2 show up in Hamiltonicity investigations.

Define:

0. Utility: is_k_tough(g,k) for graph g, real number k. (*not* a graph property - but gives properties when k is fixed).

1. is_1_tough(g)

2. is_2_tough(g)

**Comment by thenealon** [comment]
```
def is_k_tough(g,k):
    return toughness(g)>=k

def is_1_tough(g):
    return toughness(g)>=1

def is_2_tough(g):
    return toughness(g)>=2
```
