### ISSUE TITLE
Property: Bauer's sufficient condition for Hamiltonicity

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#471]
Add: is_bauer property to gt.sage

Define: is_bauer(g) = g is 2_tough and sigma_3 >= order n

1. For 2_tough, see # 468
2. For sigma_3, see: #466 

Theorem: if a graph g is_bauer then g is hamiltonian.

This theorem is quoted on p.128 of Gould's 1991 Survey.

Bauer, Douglas, et al. "Long cycles in graphs with large degree sums." Discrete Mathematics 79.1 (1990): 59-70. (attached)

[bauer-etal-long-cycles-1990.pdf](https://github.com/math1um/objects-invariants-properties/files/2058919/bauer-etal-long-cycles-1990.pdf)

**Comment by thenealon** [comment]
This uses toughness and sigma_k, commented in previous issues.

```
def is_bauer(g):
    return toughness(g)>=2 and sigma_k(g,3)>=g.order()
```
