### ISSUE TITLE
Three counterexamples

### ISSUE THREAD

**Issue by JRParrish** [math1um/objects-invariants-properties#473]
#CE to (is_hamiltonian)->((has_c4)|(has_radius_equal_diameter))
Graph('Cz') 

#CE to (is_claw_free)&(is_van_den_heuvel))->(is_hamiltonian)
Graph('E~{G')

#CE to (has_dart)&(is_two_connected))->(is_hamiltonian)
Graph('EpuG')

**Comment by yirkajk** [comment]
Thank you.
- Graph1 is the DiamondGraph
- Graph2 is the k5pendant
- Graph3 is barrus_442222b 
each already in OIP.
