### ISSUE TITLE
Sage problem with Cell120 and Cell600

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#474]
These have backwards definitions in Sage:

graphs.Cell600() has order 120

graphs.Cell120() has order 600

What to do here? At least for now a note should be added in gt.sage

**Comment by nvcleemp** [comment]
What's backwards about them? Those are the classic names: the 600-cell has 600 cells and 120 vertices, and the 120-cell has 120 cells and 600 vertices.

**Comment by yirkajk** [comment]
Sage source code cites the [600-Cell Wikipedia article](https://en.wikipedia.org/wiki/600-cell) and [120-Cell WIkipedia article](https://en.wikipedia.org/wiki/120-cell)
