### ISSUE TITLE
Add utility: is_homogeneous_set

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#477]
At a SIAM DM 2018 talk, Sergey Norin, defined a *homogeneous set* of vertices to be one that induces *either* an independent set *or* a clique.

is_homogeneous_set(g,S)==True iff S induces a clique or an independent set

this is *not* a graph property, rather a property of a set of vertices.

**Comment by yirkajk** [comment]
> S induces a clique or an independent set

I parse this as "S induces a clique" or "S in an independent set in g", yes?

```
# Defined by Sergey Norin at SIAM DM 2018
def is_homogenous_set(g, s):
    """
    Set of vertices s is homogenous if s induces a clique or s is an independent set.
    """
    induced_g = g.subgraph(s)
    return induced_g.is_clique() or g.is_independent_set(s)
```
