### ISSUE TITLE
Add more degree invariants to GT

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#482]
Add:

1. card_degree_two_vertices = the number of degree 2 vertices

2. card_order_minus_one_vertices = the number of vertices of degree equal to order - 2 (= n-2)

3. card_max_degree_vertices = the number of vertices of degree equal to the maximum degree

4. card_min_degree_vertices = the number of vertices of degree equal to the minimum degree

**Comment by yirkajk** [comment]
What is the bit at the end of the second item after n-2 ?

**Comment by math1um** [comment]
>What is the bit at the end of the second item about n-2 ?

its just a note that i'm using "n" for order. so, order-2 = n-2

**Comment by yirkajk** [comment]
Item number two is labeled "card_order_minus_one_vertices" but you have n-2.
Did you want order_minus_one, order_minus_two, or both invariants?

**Comment by math1um** [comment]
oh, got it. yes, i meant n-1.
