### ISSUE TITLE
Add property: has 2 simplicial vertices

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#486]
A class of graphs called 2-trees has exactly 2 simplicial vertices.

has_two_simplicial_vertices(g) = True iff card_simplicial_vertices == 2

See: #484

**Comment by yirkajk** [comment]
Named `has_exactly_two_vertices`

**Comment by yirkajk** [comment]
Doh, I keep making typos.
The name is indeed `has_exactly_two_simplical_vertices` in the code.
Just my comment was wrong.
