### ISSUE TITLE
Add utility: pyramid encapsulation of a graph

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#495]
The pyramid a is a graph with pebbling number > order. This construction gives an infinite family of graphs with oebbling number > order.

-start with a pyramid with inner triangle vertices 0,1,2
-take any graph G, make its vertices adjacent to every vertex in 0,1,2

```
def pyramid_encapsulation(g):
    n = g.order()
    pe=graphs.CompleteGraph(3)
    pe = pe.disjoint_union(g)
    V = pe.vertices()
    for v in [V[i] for i in [0,1,2]]:
        for w in [V[j] for j in [3..(n+2)]]:
            pe.add_edge(v,w)
    pe.add_vertices([n+3,n+4,n+4])        
    pe.add_edges([(n+3,V[0]),(n+3,V[1]),(n+4,V[1]),(n+4,V[2]),(n+5,V[2]),(n+5,V[0])])   
    pe.relabel()   
    return pe
```
Add the above comments to the doctest.

**Comment by yirkajk** [comment]
Is the attached picture a pyramid?
![image](https://user-images.githubusercontent.com/1184924/41244876-6837d690-6d74-11e8-9be5-fdbd4c662fbb.png)
And, for any graph g, we want to connect every vertex of g to vertices [0,1,2] in this pyramid?

**Comment by math1um** [comment]
Yes, that's a pyramid. And yes, you want to attached every vertex of g to each of 0,1 and 2. The pyramid is a pebbling Class1 graph (the pebbling number is order+1, it must be greater than 6 as if you put 3 pebbles on each of two corner vertices, you can't reach the other corner vertex - there's no way to move a pebble there) and this construction will yield new graphs all of which are also Class0.
