### ISSUE TITLE
Add graph: Thomassen's hypohamilton graph

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#507]
See 1974b on:
https://en.wikipedia.org/wiki/Hypohamiltonian_graph

A note of some sort should be added to file that this graph is hypohamiltonian.

**Comment by yirkajk** [comment]
The hypohamiltonian graph with girth 4 is thomassen32.
The hypohamiltonian graph with girth 3 is thomassen60.
Both were recently added in Issue #414, using those names.
