### ISSUE TITLE
Add graph: hypohamiltonian graph

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#508]
See Fig.11, p.163, of Molluzzo paper:

Molluzzo, John C. "Some Hamiltonian counterexamples." Annals of the New York Academy of Sciences 328.1 (1979): 157-165. (attached)

[molluzzo-some-hamiltonian-counterexamples-1979.pdf](https://github.com/math1um/objects-invariants-properties/files/2086844/molluzzo-some-hamiltonian-counterexamples-1979.pdf)

**Comment by yirkajk** [comment]
This is thomassen34.
Recently added in Issue #414.
