### ISSUE TITLE
Add Haemers bound and Li-Zhang upper bounds for alpha 

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#51]
p.147 of attached paper. make sure to find the bounds for non-regular graphs. (the incorrect thorem from willis' thesis was for regular graphs). 
[li-zhang-eigenvalue-bounds-2014.pdf](https://github.com/math1um/objects-invariants-properties/files/1029833/li-zhang-eigenvalue-bounds-2014.pdf)

**Comment by big-math** [comment]
Li-Zhang Upper Bound 1
```
#li-zhang bound
#alpha(G)<=((Delta - delta - minEigenvalue)/Delta)*order
li_zhang_thm = lambda g: ((max(g.degree())-min(g.degree())-min(g.adjacency_matrix().eigenvalues()))/max(g.degree()))*g.order()
```
