### ISSUE TITLE
Create 'fast mode' for conjecturing using only precomputed values

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#510]
The idea is this: you give Conjecturing graphs, invariants (or properties) and a precomputed database, and in "fast mode" the program will only - and automatically - use the graphs and invariants that exist in the precomputed database (that is, no table building computations are done) and the program will start conjecturing ASAP on whatever data is available.

The function might be conjecturing_fast, take the same parameters as conjecturing, but first builds a new fast_objects and fast_invariants, given the precomputed_database, and *then* feed that to Conjecturing - so it would then just call conjecturing(fast_objects, fast_invariants, invariant, precomputed).

Sometimes you just want conjectures *fast*!

**Comment by nvcleemp** [comment]
This should be easy to write. Examples of the required calls are already available in the functions which update the database of precomputed values.

It would also be nice if such a fast function has an option which lets it print the objects, invariants, properties which are not used.

Of course there is one difficulty: sometimes skipping one invariant will add several graphs, or by just skipping one graph you might be able to add several invariants.
