### ISSUE TITLE
Add Property is_oberly_sumner, and related sufficient condition for Hamiltonicity

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#515]
A graph is_oberly_sumner if it has order at least 3, is_two_connected and is_claw_free and is_F_free.

A theorem of Oberly and Sumner says: if a graph has order at least 3, is 2-connected and has no claw or F subgraph then it has a hamiltonian cycle.

See: Gould survey, p.135, Theorem 3.3:

Gould, Ronald J. "Updating the Hamiltonian problem—a survey." Journal of Graph Theory 15.2 (1991): 121-157:
https://github.com/math1um/objects-invariants-properties/files/2058537/gould-hamilton-survey-1991.pdf

**Comment by yirkajk** [comment]
is_F_free defined in Issue #514
