### ISSUE TITLE
Add property and theorem: broersma_veldman_gould

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#519]
A sufficient condition for Hamiltonicity is: if 2-connected, claw-free and has diameter==2 (all diameter==1 graphs with at least order 3 are complete and this Hamiltonian).

def. broersma_veldman_gould(g) iff g is 2-connected, g is claw-free and g.diameter()==2.

This is reported as p.135, Cor. 3.8 in Gould's 1991 survey:

Gould, Ronald J. "Updating the Hamiltonian problem—a survey." Journal of Graph Theory 15.2 (1991): 121-157:
https://github.com/math1um/objects-invariants-properties/files/2058537/gould-hamilton-survey-1991.pdf

**Comment by yirkajk** [comment]
Coding the property with diameter <= 2, for completeness.
