### ISSUE TITLE
Add graph

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#52]
I don't remember the significance of this one!
[graph_for_gt.pdf](https://github.com/math1um/objects-invariants-properties/files/1029881/graph_for_gt.pdf)

**Comment by PratipRana** [comment]
'Iw?EthkF?'

**Comment by nvcleemp** [comment]
It's a trigonal antiprism with a capped top face. I don't know if that rings a bell.

**Comment by rbarden** [comment]
Added as trig_antiprism.

**Comment by nvcleemp** [comment]
Maybe also add `capped` or `partial_capped` to the name since it is not a trigonal antiprism.

**Comment by rbarden** [comment]
Added capped to the name.
