### ISSUE TITLE
Add property and theorem: chvatals_condition

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#521]
Let the vertices of a graph G, v1,v2,...,vn, have degrees d1, d2,...,dn, ordered from smallest to largest.

Chvatal's condition is: for n>=3 and for each i in {1,2,..,n} either i>=(n/2) or d_i>i or d_{n-i}>=n-1

Chvatal's theorem: if Chvatal's condition holds then the graph is Hamiltonian. (This is a sufficient condition for a graph to have a Hamilton cycle).

See, Thm 1 in:
Chvátal, Václav. "On Hamilton's ideals." Journal of Combinatorial Theory, Series B 12.2 (1972): 163-168. (attached)

[chvatal-hamilton-ideals-1972.pdf](https://github.com/math1um/objects-invariants-properties/files/2112413/chvatal-hamilton-ideals-1972.pdf)

**Comment by yirkajk** [comment]
The last predicate in Chvatal's condition is d_{n-i} >= n-i, not n-1.
