### ISSUE TITLE
Add invariant: hamiltonian_index

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#522]
Let G be a connected graph, and L(G) be its line graph. This can be iterated: G, L(G), L(L(G)), etc. Let L^i(G) be the line graph of L^{i-1}(G). Call L^i(G) the ith line graph iterate.

Chartrand proved that, for a non-path-graph, a line graph iterate of G is hamiltonian.

def. line_graph_hamiltonicity_index(G) = 0 if G is hamiltonian, and otherwise i for the smallest i where L^i(G) is Hamiltonian.

CHANGED NAME: Gould (1991) calls this "hamiltonian_index".

How to define line_graph_hamiltonicity_index(path)? No iterate will *ever* be Hamiltonian. We coud return a "fail" or +Infinity. Which is better here?

See Thm 2 in:
Chartrand, Gary. "On hamiltonian line-graphs." Transactions of the American Mathematical Society 134.3 (1968): 559-566. (attached)

[chartrand-hamiltonian-line-graphs-1968.pdf](https://github.com/math1um/objects-invariants-properties/files/2112548/chartrand-hamiltonian-line-graphs-1968.pdf)

**Comment by yirkajk** [comment]
Chartrand calls this the "Hamiltonian index of G", so I'll use that name.
Also, they prove an upper bound of order-3, which may be useful.

**Comment by yirkajk** [comment]
Chartrand defines that the index does not exist for simple paths. And, lately, we've been leaning towards throwing errors more than returning values which we define.
A good rule is to be consistent, so I will define this function to throw a ValueError if it receives a path graph. The user can decide what to do if/when this occurs.
