### ISSUE TITLE
Fix doctest: is_biclique

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#524]
The doctest has:

sage: is_biclique(bow_tie)

but bow_tie isn't defined as this name (its so common that maybe we should?). 

GT uses graphs.ButterflyGraph() instead.

**Comment by yirkajk** [comment]
Found the problem. gt originally had a bow_tie, but in commit 65b4fa5 it was removed and replaced with the sage graph graphs.ButterflyGraph().
So... in the future, need to do a Ctrl+f before commits!
I'll correct this.

**Comment by rbarden** [comment]
My bad...
