### ISSUE TITLE
Conflicting definitions of common_neighbors

### ISSUE THREAD

**Issue by nvcleemp** [math1um/objects-invariants-properties#528]
There are currently two functions named `common_neighbors`. One is defined in `invariants.sage` and takes three arguments. The other is defined in `utilities.sage` and takes two arguments.

The suggestion would be to keep the version which takes two arguments since it is more general.

**Comment by yirkajk** [comment]
I did not find any call to the 2-argument `common_neighbors(g, s)` function defined in utilities.
So, I'm going to leave 3-argument function as is, and rename the 2-argument version `common_neighbors_of_set(g, s)`.
I'm also going to move both functions into utilities, as `common_neighbors` is not an invariant... it's a utility used by invariants.
