### ISSUE TITLE
Are there any orphaned database sql files?

### ISSUE THREAD

**Issue by yirkajk** [math1um/objects-invariants-properties#547]
As names of graphs change, we may have forgotten to update the database files.
Need to check.

**Comment by nvcleemp** [comment]
Maybe some test needs to be written which creates a list of all file names and a list of all function names. That way we can ran it for each push to the repository.

**Comment by nvcleemp** [comment]
These are currently reported as orphaned:

```
  number_of_triangles
  is_biclique
  is_flower
  is_pebbling_class0
```

**Comment by nvcleemp** [comment]
All of the orphaned files have been dealt with and there is no a Travis CI script which will fail the build if a new file gets orphaned.
