### ISSUE TITLE
Add irregularity measure invariants

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#56]
A graph is *regular* if all degrees are equal. There are various measures of *irregularity*. Pepper mentions:
- [x] max_degree - min_degree (d4fa885)
- [x] largest_eigenvalue - average_degree (collatz-singowitz?) (ff94c6e)
- [x] order/2 - randic_index (randic_irregularity) (d4fa885)
- [x] sum over all edges uv of |d(u)-d(v)|, where d(v) is the degree of v (fad6484)
- [x] (1/size) * sum over all edges of |d(u)-d(v)| (6e5f298)
- [x] variance of degrees := (1/order) * sum over all vertices (d_i^2 - average_degree) (d4fa885)

Some of these and maybe more are referenced in this Elphick-Wocjan paper:
https://arxiv.org/abs/1305.3570

**Comment by rbarden** [comment]
@math1um I'm going to add at least some of these this morning, how should I name them? irregularity_1 wouldn't be helpful at all if it pops up in a conjecture, but if we use all words, they could get unwieldily long.
