### ISSUE TITLE
number_of_triangles disappeared

### ISSUE THREAD

**Issue by nvcleemp** [math1um/objects-invariants-properties#562]
The invariant `number_of_triangles` introduced in 4ea089481bdcdcc6b8deb9a88e7c68374f4a048e has since disappeared. This is especially problematic since there are some theorems which still refer to it, and thus are currently broken.

Was there a mistake in this invariant, or was it just removed by accident?

**Comment by math1um** [comment]
Graph.triangles_count is a method now, and included in the invariants list. Maybe someone just removed the one we coded after the method became available?

**Comment by nvcleemp** [comment]
No, for some time neither were in the repository. But fine, we have a replacement now.

**Comment by nvcleemp** [comment]
All of the occurrences of `number_of_triangles` have been replaced by `Graph.triangles_count`.
