### ISSUE TITLE
Need utility function: check if a graph already exists

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#57]
It would be useful to have a function does_graph_exist(g,L) which inputs a graph g and a list of (names of?) graphs L and checks if g is isomorphic to any graph in the list.

**Comment by nvcleemp** [comment]
This should do just that, but there might be more efficient things possible (like storing canonical forms of each graph in a search tree):

`any(g.is_isomorphic(gL) for gL in L)`

**Comment by rbarden** [comment]
Added a version of this that returns all names that are isomorphic (not just returning on the first, in case there happen to be duplicates). If we need a more efficient search, it can be done later.
