### ISSUE TITLE
add gallai tree example

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#6]
see:
https://www.researchgate.net/figure/260483294_fig4_Figure-10-A-Gallai-tree-with-15-blocks

**Comment by harrisbm3** [comment]
I'm claiming this one.

**Comment by harrisbm3** [comment]
Gallai_tree = Graph(33)
Gallai_tree.add_edge(0,1)
Gallai_tree.add_edge(1,2)
Gallai_tree.add_edge(2,3)
Gallai_tree.add_edge(3,4)
Gallai_tree.add_edge(4,5)
Gallai_tree.add_edge(5,6)
Gallai_tree.add_edge(6,7)
Gallai_tree.add_edge(6,0)
Gallai_tree.add_edge(7,8)
Gallai_tree.add_edge(7,11)
Gallai_tree.add_edge(8,9)
Gallai_tree.add_edge(8,10)
Gallai_tree.add_edge(8,11)
Gallai_tree.add_edge(11,12)
Gallai_tree.add_edge(11,14)
Gallai_tree.add_edge(12,13)
Gallai_tree.add_edge(13,14)
Gallai_tree.add_edge(12,14)
Gallai_tree.add_edge(13,11)
Gallai_tree.add_edge(14,15)
Gallai_tree.add_edge(14,20)
Gallai_tree.add_edge(15,16)
Gallai_tree.add_edge(16,17)
Gallai_tree.add_edge(17,18)
Gallai_tree.add_edge(18,19)
Gallai_tree.add_edge(19,15)
Gallai_tree.add_edge(15,20)
Gallai_tree.add_edge(20,21)
Gallai_tree.add_edge(21,22)
Gallai_tree.add_edge(22,23)
Gallai_tree.add_edge(23,24)
Gallai_tree.add_edge(24,20)
Gallai_tree.add_edge(20,22)
Gallai_tree.add_edge(20,23)
Gallai_tree.add_edge(21,24)
Gallai_tree.add_edge(21,23)
Gallai_tree.add_edge(22,24)
Gallai_tree.add_edge(24,25)
Gallai_tree.add_edge(25,26)
Gallai_tree.add_edge(25,27)
Gallai_tree.add_edge(26,27)
Gallai_tree.add_edge(27,28)
Gallai_tree.add_edge(27,29)
Gallai_tree.add_edge(28,29)
Gallai_tree.add_edge(29,30)
Gallai_tree.add_edge(29,31)
Gallai_tree.add_edge(29,32)

**Comment by rbarden** [comment]
Confirmed and added. The g6 string is "`hCKGC@?G@?K?@?@_?w?@??C??G??G??c??o???G??@_??F???N????_???G???B????C????W????G????G????C"
