### ISSUE TITLE
Add alias for c7 to GT

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#602]
The cycle c7 on 7 vertices exists in GT as c7 = alpha_critical_FhCKG

It would be useful if "c7" as that name existed after the user loads GT - but of course we don't want to add it again a 2nd time.

add reference:
c7 = alpha_critical_FhCKG

**Comment by math1um** [comment]
c7 is a better name for this graph. Just change it c7.

**Comment by math1um** [comment]
c7 exists as a graph in the alpha_critical_graphs list. we'11:

1) remove the g6 string from the list (so remove 'FhCKG')

2) add a graph c7 elsewhere (say just below c6!):

c7 = graphs.CycleGraph(7)
c7.name(new = "c7")
add_to_lists(c7, graph_objects, all_graphs)


OLD:

alpha_critical_graph_names = ['A_','Bw', 'C~', 'Dhc', 'D~{', 'E|OW', 'E~~w', 'FhCKG', 'F~[KG',
'FzEKW', 'Fn[kG', 'F~~~w', 'GbL|TS', 'G~?mvc', 'GbMmvG', 'Gb?kTG', 'GzD{Vg', 'Gb?kR_', 'GbqlZ_',
'GbilZ_', 'G~~~~{', 'GbDKPG', 'HzCGKFo', 'H~|wKF{', 'HnLk]My', 'HhcWKF_', 'HhKWKF_', 'HhCW[F_',
'HxCw}V`', 'HhcGKf_', 'HhKGKf_', 'Hh[gMEO', 'HhdGKE[', 'HhcWKE[', 'HhdGKFK', 'HhCGGE@', 'Hn[gGE@',
'Hn^zxU@', 'HlDKhEH', 'H~~~~~~', 'HnKmH]N', 'HnvzhEH', 'HhfJGE@', 'HhdJGM@', 'Hj~KHeF', 'HhdGHeB',
'HhXg[EO', 'HhGG]ES', 'H~Gg]f{', 'H~?g]vs', 'H~@w[Vs', 'Hn_k[^o']

**Comment by jaritaes99** [comment]
fixed
