### ISSUE TITLE
CE to size<=(independence^2+1)+1

### ISSUE THREAD

**Issue by thenealon** [math1um/objects-invariants-properties#605]
```
Graph('OAYRKr?KGW_\k@HWW@GSd')
```

**Comment by math1um** [comment]
ADD to graphs.sage (making it ce136):

# CE to size<=(independence^2+1)+1
ce136=Graph('OAYRKr?KGW_\k@HWW@GSd')
ce136.name(new = "ce136")
add_to_lists(ce136, graph_objects, counter_examples, all_graphs)

**Comment by jaritaes99** [comment]
added
