### ISSUE TITLE
Sage ?? does not work for our functions

### ISSUE THREAD

**Issue by yirkajk** [math1um/objects-invariants-properties#610]
Running `some_command?` returns just the docstring. This works for our functions.
Running `some_command??` returns both the docstring and the source code for functions. But, when I run, for example, `is_two_connected??`, Sage reports
```   
File: /home/user/<string>
Unable to read source code (source code not available)
```

**Comment by nvcleemp** [comment]
The ?? is a IPython feature, and it is expected to not work with files loaded through the load command, because there is no source stored for them. I think I already commented in the ticket about switching to a Python module that one of the benefits would be that ?? then works.
