### ISSUE TITLE
Pineapple Graphs

### ISSUE THREAD

**Issue by thenealon** [math1um/objects-invariants-properties#614]
Pineapple Graphs are formed by taking a clique and adding a number of pendants all adjacent to the same clique vertex.  These were presented/introduced by Alex Cameron (Vanderbilt) at the 50th SE Conference.

This is a generator for pineapple graphs.

```
def pineappleGraph(s,t):
    #returns a pineapple with an s vertex clique and t pendants
    G=graphs.CompleteGraph(s)
    for i in range(t):
        G.add_edge((0,i+s))
    return G
```

**Comment by math1um** [comment]
Add pineapple definition somewhere (graphs? auxiliary functions?)

Add a couple of examples of these:

pineapple_3_4

pineapple_4_2

after you define a graph object its got to be added to one or more lists (or it will never be found)

**Comment by jaritaes99** [comment]
Added pineapple graph generator and added pineapple graphs to list of graphs
