### ISSUE TITLE
is_factor_critical property has mistake in docstring

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#616]
SHOULD BE:

sage: is_factor_critical(graphs.PathGraph(3))
        True

OLD:

def is_factor_critical(g):
    """
    Return whether or not a graph "g" is factor-critical.

    A graph is factor-critical if order is odd and removal of any vertex gives graph with perfect matching
    
    INPUT:

    -``g``-- Sage graph

    OUTPUT:

    -Boolean value

    EXAMPLES:

        sage: is_factor_critical(graphs.PathGraph(3))
        False

        sage: is_factor_critical(graphs.CycleGraph(5))
        True

**Comment by jaritaes99** [comment]
fixed
