### ISSUE TITLE
Changing Lovasz theta from built-in method to a function 

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#617]
In Issue #606 we defined a new Lovasz theta function that attempts to handle rounding error for values that are very close to an integer. We will now replace the existing built-in method (Graph.lovasz_theta()) throughout with this lovasz_theta function.

So, throughout the gt files, we need to:

(1) replace every instance of expressions like g.lovasz_theta() with lovasz_theta(g), and
(2) change the corresponding doctests, and
(3) change instances of Graph.lovasz_theta in lists like efficiently_computable_invariants to lovasz_theta.

**Comment by jaritaes99** [comment]
done
