### ISSUE TITLE
Add 2 counterexample graphs

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#629]
M. Dahir conjectured that is G and H are graphs with distance matrices Gd and Hd and 
(Gd)*(Hd)*(Gd) is similar to (Hd)*(Gd)*(Hd) then G and H are isomorphic.

This is False. Here is a counterexample pair:

G = Graph(r"K?Bcvb[nBUNO")
H = Graph(r"K?Bcv`\nFSNO")

(Gd)*(Hd)*(Gd) ~ (Hd)*(Gd)*(Hd) but G and H are not isomorphic.

**Comment by jaritaes99** [comment]
added as ce143_G and ce143_H
