### ISSUE TITLE
Add alpha_critical graphs

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#636]
There are 11 alpha-critical critical graphs in the attached paper:

1. code each one.
2. Test each one to make sure it is alpha-critical using the function in GT is_alpha_critical
3. add each to the list: alpha_critical_easy
4. mention in the docstring (or code section) they are from the paper:

Plummer, Michael, Michael Stiebitz, and Bjarne Toft. "On a special case of Hadwiger's conjecture." Discussiones Mathematicae Graph Theory 23, no. 2 (2003): 333-363.

Call them:
1. PST-6-1-a (this matches up with Figure 6.1(a))
2. PST-6-1-b
3. PST-6-1-c
4. PST-6-2-a
5. PST-6-2-b
6. PST-6-2-c
7. PST-6-3-a
8. PST-6-3-b
9. PST-6-4-a
10. PST-6-5

[plummer-stiebitz-toft-special-case-hadwigers-conjecture-2003.pdf](https://github.com/math1um/objects-invariants-properties/files/6792984/plummer-stiebitz-toft-special-case-hadwigers-conjecture-2003.pdf)

**Comment by jaritaes99** [comment]
done
