### ISSUE TITLE
ce60 is not defined?

### ISSUE THREAD

**Issue by jaritaes99** [math1um/objects-invariants-properties#637]
The code shows 
# CE to independence_number(x) >= -1/2*diameter(x) + lovasz_theta(x)
$MxF|ADGGMBW`ANV_IKw??DRkY\KOCW??P_?ExJDSAg')
ce60.name(new = "ce60")
add_to_lists(ce60, graph_objects, counter_examples, all_graphs)

and there is no definition of it? is $MxF|ADGGMBW`ANV_IKw??DRkY\KOCW??P_?ExJDSAg') the g6 string?

**Comment by thenealon** [comment]
' and ) are not g6 characters (g6 strings contain ascii codes 63-126), so
this looks like the truncated end of a g6 string call used to construct the
graph, i.e., it is probably Graph('....Ag').  Not tons of hope for
recovering the graph from only that info, although we could probably try to
find another counterexample to the same conjecture.

**Comment by jaritaes99** [comment]
I just double checked and it was a $ at the beginning, meaning I had to scroll to the beginning of the line, it is defined properly
