### ISSUE TITLE
Add line graph of K3,3

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#65]
K3,3 is the complete bipartite graph with partite sets of cardinality 3 and 3.

The line graph L(G) of a graph G has the edges of G as the vertex set of L(G) and two vertices of L(G) are adjacent if their corresponding edges in G are incident.

Both steps should be built-in to Sage

**Comment by shivejl** [comment]
I'll do this.

**Comment by shivejl** [comment]
Feel free to check:

`'H{S{aSf'`

**Comment by rbarden** [comment]
Added.
