### ISSUE TITLE
Add geometric_length_of_degree_sequence invariant

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#69]
this is the square root of (the sum of the squares of the degrees of the vertices) of a given graph

it was defined by R. Pepper in an unpublished paper on graph irregularity

**Comment by thenealon** [comment]
def geometric_length_of_degree_sequence(g):
    sum=0
    for d in g.degree():
        sum=sum+d^2
    return sqrt(sum)

**Comment by nvcleemp** [comment]
This is also something for which list comprehensions are fairly useful:

´´´
def geometric_length_of_degree_sequence(g):
    return sqrt(sum(d^2 for d in g.degree()))
´´´
