### ISSUE TITLE
properties that need to be computed

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#7]
- [ ] is_cartesian_product for haemers is missing.
- [ ] is_haggkvist_nicoghossian for haemers is missing.
- [ ] is_generalized_dirac for haemers is missing.
- [ ] is_lindquester for haemers is missing.
- [ ] is_fan for haemers is missing.
- [ ] is_lindquester for haemers is missing.
- [ ] is_fan for haemers is missing.
- [ ] matching_covered for haemers is missing.
- [ ] matching_covered for haemers is missing.
- [ ] is_locally_two_connected for haemers is missing.
- [ ] is_hamiltonian for haemers is missing.
- [ ] is_class1 for haemers is missing.
- [ ] is_class1 for alon_seymour is missing.
- [ ] is_class1 for alpha_critical_Hj\x{F{ is missing.
- [ ] is_class1 for K02K13 is missing.
- [ ] is_class1 for C28Pow08 is missing.
- [ ] is_class2 for Meredith Graph is missing.
- [ ] is_class2 for haemers is missing.
- [ ] is_class2 for alon_seymour is missing.
- [ ] is_class2 for alpha_critical_Hj\x{F{ is missing.
- [ ] is_class2 for K02K13 is missing.
- [ ] is_class2 for C28Pow08 is missing.
- [ ] is_anti_tutte2 for haemers is missing.
- [ ] has_lovasz_theta_equals_cc for Schläfli graph is missing.
- [ ] has_lovasz_theta_equals_cc for haemers is missing.
- [ ] has_lovasz_theta_equals_cc for c3mycielski4 is missing.
- [ ] has_lovasz_theta_equals_cc for W20 is missing.
- [ ] has_lovasz_theta_equals_cc for W18 is missing.
- [ ] has_lovasz_theta_equals_alpha for haemers is missing.
- [ ] is_chvatal_erdos for haemers is missing.
- [ ] is_traceable for haemers is missing.

**Comment by yirkajk** [comment]
Will be redoing this soon, Summer 18.
Will open a new issue as needed.
