### ISSUE TITLE
Add unit distance graph

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#70]
on p.58 of the attached paper
[chilakamarri-unit-distance-graph-problem-survey-1993.pdf](https://github.com/math1um/objects-invariants-properties/files/1032206/chilakamarri-unit-distance-graph-problem-survey-1993.pdf)

**Comment by shivejl** [comment]
I'll do this.

**Comment by shivejl** [comment]
Feel free to check:

`'Hw?Cyw{'`

**Comment by math1um** [comment]
Appears in Cranston paper:
http://www.people.vcu.edu/~dcranston/pubs/fractional-plane.pdf
