### ISSUE TITLE
Add ciliate graphs C4,1, C4,2, C6,1

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#71]
on p.27 of attached
[larson-hammack-taylor-independence-cartesian-product-published.pdf](https://github.com/math1um/objects-invariants-properties/files/1032221/larson-hammack-taylor-independence-cartesian-product-published.pdf)

**Comment by shivejl** [comment]
I'll do this.

**Comment by shivejl** [comment]
Feel free to check:
C4,1: ` 'G?_gqK'`
C4,2: `'K?`@?_G?gB?b'`
C6,1: `'K??C?SEO?acE'`
