### ISSUE TITLE
Add Steinberg's conjecture G1 graph

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#72]
on p.454 of attached
[cohen-addad-hebdige-kral-li-salgado-steinbergs-conjecture-2017.pdf](https://github.com/math1um/objects-invariants-properties/files/1032233/cohen-addad-hebdige-kral-li-salgado-steinbergs-conjecture-2017.pdf)

**Comment by harrisbm3** [comment]
I'll do this one

**Comment by harrisbm3** [comment]
Graph('N?CWGOOOH@OO_POdCHO')

'N?CWGOOOH@OO_POdCHO'
