### ISSUE TITLE
Add Steinberg's conjecture G2 graph

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#73]
On p.454 on Steinberg's Conjecture paper in Issue #72

**Comment by harrisbm3** [comment]
Ill do this one

**Comment by harrisbm3** [comment]
'ihCGGC@?G?o@o???_?H?@??K??Go?K?G??B???@gW?????G???P???K???@????P???@????B????BG????_?G??G?????G????A?O???H?????C????`?_???CO??????P?K????o@_????o'

I am also posting the code below 
`
G2 = Graph()

G2.add_edge(1,2)
G2.add_edge(1,13)
G2.add_edge(1,20)
G2.add_edge(1,12)

G2.add_edge(2,3)
G2.add_edge(2,13)

G2.add_edge(3,4)
G2.add_edge(3,16)

G2.add_edge(4,5)
G2.add_edge(4,19)

G2.add_edge(5,6)
G2.add_edge(5,19)
G2.add_edge(5,23)

G2.add_edge(6,7)
G2.add_edge(6,23)

G2.add_edge(7,8)
G2.add_edge(7,36)

G2.add_edge(8,9)
G2.add_edge(8,42)

G2.add_edge(9,10)
G2.add_edge(9,41)
G2.add_edge(9,42)

G2.add_edge(10,11)
G2.add_edge(10,41)

G2.add_edge(11,12)
G2.add_edge(11,33)

G2.add_edge(12,20)

G2.add_edge(13,14)
G2.add_edge(13,21)

G2.add_edge(14,15)
G2.add_edge(14,21)

G2.add_edge(15,16)
G2.add_edge(15,17)

G2.add_edge(16,17)

G2.add_edge(17,18)

G2.add_edge(18,19)
G2.add_edge(18,22)

G2.add_edge(19,22)

G2.add_edge(20,24)
G2.add_edge(20,25)

G2.add_edge(21,22)
G2.add_edge(21,26)

G2.add_edge(22,26)

G2.add_edge(23,27)
G2.add_edge(23,28)

G2.add_edge(24,25)
G2.add_edge(24,29)

G2.add_edge(25,38)
G2.add_edge(25,30)

G2.add_edge(26,30)
G2.add_edge(26,31)

G2.add_edge(27,28)
G2.add_edge(27,39)
G2.add_edge(27,31)

G2.add_edge(28,32)

G2.add_edge(29,33)

G2.add_edge(30,31)
G2.add_edge(30,38)

G2.add_edge(31,39)

G2.add_edge(32,36)
G2.add_edge(32,35)

G2.add_edge(33,34)

G2.add_edge(34,37)

G2.add_edge(35,36)
G2.add_edge(35,40)

G2.add_edge(37,38)
G2.add_edge(37,41)

G2.add_edge(38,41)

G2.add_edge(39,40)
G2.add_edge(39,42)

G2.add_edge(40,42)
`

**Comment by PratipRana** [comment]
I think this is actually fig 2 of the paper. We need to build fig 3.
