### ISSUE TITLE
Add Cheeger_constant graph invariant

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#74]
See:
https://en.wikipedia.org/wiki/Cheeger_constant_(graph_theory)

This shows up in practical problems like PageRank:
http://www.pnas.org/content/104/50/19735.full

**Comment by cjoshea9** [comment]
Working code for the Cheeger constant. Testing done.

`def cheeger_constant(g):
    """
    Defined at https://en.wikipedia.org/wiki/Cheeger_constant_(graph_theory)
    
    sage: cheeger_constant(p2)
    1
    sage: cheeger_constant(k5)
    3
    sage: cheeger_constant(paw)
    1
    """
    
    
    n = g.order()
    upper = floor(n/2)
    
    v = g.vertices()
    SetV = Set(v)
    
   
    temp = g.order()
    best = n
    
    for i in [1..upper]:
        for s in SetV.subsets(i):
            #print 's is {}'.format(s)
            count = 0
            for u in s:
                #print 'u is {}'.format(u)
                for w in SetV.difference(s):
                    #print 'w is {}'.format(w)
                    for e in g.edges(labels=false):
                        if Set([u,w]) == Set(e):
                            count += 1
                            #print 'count is {}'.format(count)
            temp = count/i
            if temp < best:
                best = temp
    return best`
