### ISSUE TITLE
Add largest number of common vertices for a pair invariant

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#75]
-Scan through all pairs of vertices
-find the neighborhood of that pair and record its cardinality
-return the maximum over all pairs

(a graph is a flower/windmill iff this is 1)

**Comment by thenealon** [comment]
This is in gt_sage as max_common_neighbors(g)

**Comment by rbarden** [comment]
Since it is in there, I'll close this issue.
