### ISSUE TITLE
Add smallest number of common vertices for a pair invariant

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#76]
-Scan through all pairs of vertices
-find the neighborhood of that pair and record its cardinality
-return the minimum over all pairs

(for most graphs this is probably 0. for complete graphs it will be n-3)

**Comment by thenealon** [comment]
This is in gt.sage as  min_common_neighbors(g)

**Comment by rbarden** [comment]
Since it is already in there, I'll close this.
