### ISSUE TITLE
alpha lower bound conjecture: matching - sigma_2

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#77]
Is this true (i found this in old notes)?

alpha >- matching_number - sigma_2

sigma_2 is the smallest sum of degrees of non-adjacent vertices. both invariants are included in gt.sage

**Comment by thenealon** [comment]
Conjecture is false; graph 'iQipA?OB?X@gXA?II`?{M?Q?i_?WM_OABKHE@AXGBX_GOhAD?gD???o@Sa?@@]?@Bx_kmO`aEwF}D`{P@`?`_?]@CQIRh^SFCF_[FAg?DI??XHGHI@__?De@OoT@O?LG?qQI?aBKH_C??BSP_' has independence number=12, matching number=21, and sigma_2=8.  Sorry for the huge counterexample (order 42; the answer to life, the universe and everything).

Counterexample was found randomly, not constructed.

**Comment by thenealon** [comment]
Smaller counterexample: 'cGO_?CCOB@O?oC?sTDSOCC@O???W??H?b???hO???A@CCKB??I??O??AO@CGA???CI?S?OGG?ACgQa_Cw^GP@AID?Gh??ogD_??dR[?AG?' found on a miniscule 36 vertices.

**Comment by rbarden** [comment]
Added.
