### ISSUE TITLE
Add 4-pan, kite, stool, co-domino graphs

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#78]
These are on p.1691 of the attached paper.

They are likely already in gt.sage, but if not *should* be included.

[barrus-molnar-strong-havel-hakimi-property-2016.pdf](https://github.com/math1um/objects-invariants-properties/files/1032315/barrus-molnar-strong-havel-hakimi-property-2016.pdf)

**Comment by shivejl** [comment]
4-pan: `'DBw'`
kite: ` 'DJk'`
stool: `'E@ow'`
co-domino: `'ETXW'`
