### ISSUE TITLE
Add the Paley graph with 101 vertices

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#79]
Noga Alon used this to disprove Graffiti's conjecture 22.

(Is this unambiguously defined?)

Fajtlowicz's Written On the Wall with conjectures and this comment is attached (a 22 page truncation of the whole huge file).
[fajtlowicz-wow-july2004-truncated.pdf](https://github.com/math1um/objects-invariants-properties/files/1032391/fajtlowicz-wow-july2004-truncated.pdf)

**Comment by thenealon** [comment]
I'll add this; it is certainly unambiguously defined (vertices are adjacent when their difference is a quadratic residue)

**Comment by thenealon** [comment]
Here's a Paley generator:

def Paley(q):
    field = GF(q)
    return Graph([field, lambda i,j: i != j and (i-j).is_square()])
