### ISSUE TITLE
Chartrand Fig 1.8 (G, F1, F2)

### ISSUE THREAD

**Issue by shivejl** [math1um/objects-invariants-properties#83]
G is a graph on 7 vertices with 8 edges. It is composed of a 4-cycle and a 6-cycle. Its degree sequence is 3,3,2,2,2,2,2.
F1 is a graph of order 7 and size 10. It is composed of two 3-cycles and two 4-cycles. Its degree sequence is 4,4,3,3,2,2,2.
F2 is a graph of order 7 and size 10. It is composed of two 3-cycle and two 4-cycles. Its degree sequence is 5,3,3,2,2,2,2.

**Comment by shivejl** [comment]
G: `'Fo@Xo'`
F1: `'F@J]o'`
F2: ` 'F?NVo'`

**Comment by rbarden** [comment]
Please confirm F1. 
F2 has a different degree sequence than the one you provided.

**Comment by shivejl** [comment]
My apologies. F1 has four 4 cycles. F2 has a degree sequence of 5,3,3,3,2,2,2.
