### ISSUE TITLE
Rename star graphs in gt.sage

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#86]
The star graph s3 could either be a graph with 3 vertices or 3 edges (4 vertices). 

a better (less confusable) name for the star graphs would be k_1_n where n is the number of rays. so Sage's s3 would be k_1_3 (the complete bipartite graph with partite sets of cardinality 1 and n).

change all sn definitions in gt.sage from sn to k_1_n (for clarity)

**Comment by rbarden** [comment]
Changed.
