### ISSUE TITLE
Add NB counterexample graph

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#88]
NB found Graph('x??C?O?????A?@_G?H??????A?C??EGo?@S?O@?O??@G???CO???CAC_??a?@G?????H???????????O?_?H??G??G??@??_??OA?OCHCO?YA????????A?O???G?O?@????OOC???_@??????MCOC???O_??[Q??@???????O??_G?P?GO@A?G_???A???A@??g???W???@CG_???`_@O??????@?O@?AGO?????C??A??F??????@C????A?E@L?????P@`??') is a CE to conjecture:
independence_number(x) <= 10^order_automorphism_group(x) 

n=57, alpha = 25, automorphism group is trivial

**Comment by rbarden** [comment]
Added.
