### ISSUE TITLE
Conj. independence_number(x) <= 2*maximum(welsh_powell(x), max_even_minus_even_horizontal(x)) is false

### ISSUE THREAD

**Issue by thenealon** [math1um/objects-invariants-properties#91]
CE:
`Graph('mG???GP?CC?Aa?GO?o??I??c??O??G?ACCGW@????OC?G@?_A_W_OC@??@?I??O?_AC?Oo?E@_?O??I??B_?@_A@@@??O?OC?GC?CD?C___gAO?G??KOcGCiA??SC????GAVQy????CQ?cCACKC_?A?E_??g_AO@C??c??@@?pY?G?')`

**Comment by rbarden** [comment]
Added.
